app/language/fr/welcome.php
hello I just added the French language. I am new on github and I hope to
have the rules. thank you.
=> Add french language

app/helpers/database.php
This change allows to use the FETCH_CLASS fetch style, retrieving an instance of the class passed in the arguments from a result set.
=> Add support to PDO::FETCH_CLASS

app/Helpers/Csrf.php
Protect post data from csrf attacks.
=> CSRF helper

app/Helpers/Database.php
Update method had stray $'s applied fix in capekfilip's comment.
=> Removed stray $

app/Helpers/Paginator.php, app/Helpers/page_eloq.md
Added methods for using query builders skip and take parameters.
=> Added support for eloquent query builder skip take

app/Helpers/page_eloq.md
Update in conjunction with `app/Helpers/Paginator.php`:
- fix typo in namespace region
- add some lowercase (private variable) and camelCase (methods)
- syntax highlighting
=> Suggestion to update page_eloq.md

app/language/de/Welcome.php
The translation was not right for the german language, so i fixed it.
=> Fixed the wrong translation (Maybe google translator?) to right german

app/views/welcome/welcome.php
fixed an error, the first letter of Welcome was not in uppercase like the file
=> fixed an error while loading language

app/language/nl/Welcome.php
=> Fixing nl translation

app/Core/Router.php
On some servers the old routing style was not working properly or not
working at all
=> Fix not working old style routing

app/Core/Logger.php, app/Helpers/Arr.php
Update Core\Logger 
Add Helpers\Arr
=> Update Core\Logger and add Helpers\Arr

app/language/cs/Welcome.php
add cs-cz language for welcome controller
=> Add cs-CZ language

app/Helpers/Csrf.php
csrf token kept being regenerated this is now resolved
=> Swapped varibles $csrf_token and $stored_time

app/Helpers/Form.php
as this link
http://www.w3schools.com/bootstrap/bootstrap_forms.asp
they suggest to use
<form role="form">
=> Add role attribute for <form> tag in method open

app/Helpers/Form.php
Add select required, input required, input accept, input max length, textbox max length, textbox required
=> Add tags input, textbox and select

app/Helpers/Url.php
=> add function to remove accents from url

app/Helpers/Date.php
function will return an array of business dates between 2 dates. 
Weekends are set by setting the integer value of the start day of the week. 
where 1 = Monday, 7 = Sunday. 
ie Normal weekend - Sat & Sun set at 6.
bank holidays can be added in $holiday array if required.
=> add function to return business dates

app/Helpers/Data.php
I found this to be useful when used with user registration and confirm registration emails.
=> added key generation method to data helper class

app/Helpers/Paginator.php
The class was in the wrong place and so did not show when he was active.
=> Change class active of span to li

app/Helpers/Url.php
Change to variable $ custom , as the variable , ADMIN_TEMPLATE is not defined anywhere
=> Alter variable ADMIN_TEMPLATE not exist in config

app/Core/Config.example.php
Simple update in Config.Example.php file
=> Simple update in Config.Example.php file

app/Helpers/Paginator.php
These two commits fix some small issues with formatting/structure to fully adthere to bootstrap's way of doing things.
=> Fix small issues in Pagination

app/Core/View.php
Could somebody check if everything works correct (just in case)?
=> View class refactoring

app/Helpers/Date.php
Takes a month/year as input and returns the number of days in that month
=> New function daysInMonth

app/Helpers/Request.php, app/Helpers/SimpleCurl.php
I think can be useful that Request has a get method too, maybe there should be a xss filter. At SimpleCurl i added a $params check, because if $params is null or an empty array the $params concatenation is not necessary and can to produce errors.
=> added get function to Request and check on SimpleCurl

app/Helpers/Form.php
Found this attribute missing when using Jquery validate so I have added it to the text field.
I will add others as I find them.
=> Added min length attribute to text field

app/Controllers/Demo.php, app/Core/ClassicRouter.php, system/Core/Config.example.php, system/Core/Error.php, system/Core/Route.php, system/Core/Router.php, system/Core/routes.php, system/Helpers/Request.php, system/Helpers/Url.php
This pull request contains the Improved Routing components discussed on https://github.com/simple-mvc-framework/framework/issues/222
=> Replacement of SMVC Router with an Improved Routing

system/Helpers/Date.php
As the title said. Adding new function to get age (years) from a birthday (timestamp) also improved some PHPDoc blocks and declared a variable to prevent undeclared usage in the Date helper.
=> Adding age from birthday function, improved PHPDoc and fixed undeclared variable in Date helper.

app/Controllers/Demo.php, app/Controllers/Welcome.php, system/Core/routes.php
You have to import the testdata from the sql export:
[cardemo_database.sql.txt](https://github.com/simple-mvc-framework/framework/files/61510/cardemo_database.sql.txt)
=> Moving sample from index page to the demo page with route /database.

app/Controllers/Demo.php, app/Models/Entities/Car.php, app/Services/Database/Car.php, system/Database/DatabaseService.php, system/Database/Engine/Engine.php, system/Database/Engine/MySQLEngine.php, system/Database/EngineFactory.php, system/Database/Entity.php, system/Database/Service/MySQLService.php, system/Database/Service/Service.php
Moving database from \Smvc\Core\Database to \Smvc\Database
=> Moving database from \Smvc\Core\Database to \Smvc\Database

app/Config/bootstrap.php, app/Config/constants.php, app/Config/routes.php, app/Core/ClassicRouter.php, public/index.php
Some Routing small fixes and **ClassicRouter** optimization (for speed).
=> Optimize and speed-up the ClassicRouter, other Routing small fixes.

app/Config/routes.php, app/Core/ClassicRouter.php, system/Core/Route.php, system/Core/Router.php
Like the Pull Request title say, there are some further optimizations and Routing's fine-tuning for speeding-up its response.
=> Further optimization and speed-up of the Routing.

app/templates/default/footer.php, app/templates/default/header.php
For more information see http://blog.getbootstrap.com/2015/11/24/bootstrap-3-3-6-released/
=> Upgrade Bootstrap to 3.3.6

.htaccess, app/Config/bootstrap.php, app/Config/config.php, app/Config/constants.php, app/Config/functions.php, app/Config/routes.php, app/Core/ClassicRouter.php, app/Views/Error/error404.php, public/index.php, public/templates/default/footer.php, public/templates/default/header.php, server.php, system/Config.php, system/Core/Controller.php, system/Core/View.php, system/Database/DatabaseService.php, system/Database/EngineFactory.php, system/Error.php, system/Helpers/Assets.php, system/Helpers/Database.php, system/Helpers/PhpMailer.php, system/Language.php, system/Logger.php, system/Modules/Manager.php, system/Net/Cookie.php, system/Net/Request.php, system/Net/Route.php, system/Net/Router.php, system/Net/Url.php
This pull-request a further refactoring of SMVC's System, looking for a better usability and logical grouping of the System's components. Then, the main an often used utility Classes, like **Config**, **Language**, **Error**, also **Logger** we are moved from namespace **\Smvc\Core** into base one, **\Smvc**. So, right now, we have:
**\Smvc\Config**
**\Smvc\Error**
**\Smvc\Language**
**\Smvc\Logger**
In other hand, the Routing components, **\Smvc\Core\Route** and **\Smvc\Core\Router** are moved in their own own namespace: **\Smvc\Net**. In the same namespace arrived the main network associated helpers: **\Smvc\Helpers\Request**, and **\Smvc\Helpers\Url**. So, right now, we have:
**\Smvc\Net\Request**
**\Smvc\Net\Route** 
**\Smvc\Net\Router**
**\Smvc\Net\Url**
As a new, but very useful …
=> Further refactoring of SMVC's System.

server.php
Like title say...
Usage, from ROOT:
```
php -S localhost:8080 -t public/ server.php
```
=> Fix standalone server.

public/index.php
=> Fix behaviour in standalone server.

app/Config/functions.php, app/Config/routes.php, app/Controllers/ThemedDemo.php, app/Controllers/Welcome.php, app/Core/ThemedController.php, app/Templates/Default/Assets/css/style.css, app/Templates/Default/Layouts/default.php, app/Views/ThemedDemo/subpage.php, app/Views/ThemedDemo/welcome.php, app/Views/Welcome/subpage.php, app/Views/Welcome/welcome.php, system/Core/Controller.php, system/Core/View.php, system/Net/Router.php
This pull-request implement the improved Core engine, sporting an enhanced **\Smvc\Core\Controller** and **\Svmc\Core\View**.
The details you known from **SMVC Restructure Mega-Thread**.
=> 3.0 - improved Core components

app/Config/config.php, system/Database/Engine/SQLiteEngine.php, system/Database/EngineFactory.php
All tested, but please test too :+1: 
Also added sample config, and adding constant for using with the factory.
=> Adding SQLite Engine (pdo) and improving engine structure.

app/Controllers/Demo.php, system/Database/Engine/MySQL.php, system/Database/Engine/SQLite.php, system/Database/Manager.php, system/Database/Service.php, system/Database/Service/MySQL.php, system/Helpers/Database.php
All factories and instance managers are now Managers instead of Factory.
=> EngineFactor renamed to Manager

app/Config/bootstrap.php, app/Config/config.php, app/Config/constants.php, app/Config/functions.php, app/Controllers/Demos/Classic.php, app/Controllers/Demos/EventListener.php, app/Controllers/Demos/Events.php, app/Controllers/Demos/Themed.php, app/Core/ClassicController.php, app/Core/ClassicRouter.php, app/Core/ThemedController.php, system/Config.php, system/Core/Controller.php, system/Core/Event.php, system/Core/View.php, system/Events/Listener.php, system/Events/Manager.php, system/Helpers/ReCaptcha.php, system/Helpers/Validator.php, system/Language.php, system/Modules/Config.php, system/Modules/Manager.php, system/Net/Response.php, system/Net/Route.php, system/Net/Router.php
@LuckyCyborg The only change is the correction of the double @@ characters :smile:
=> 3.0 fix email

README.md
Changes:
- introducing the framework at the beginning
- add a few links for better understanding
- markdown the installation instructions
=> 2.2 beautify README.md

README.md
Changes:
- markdown the instructions
- add a link to report issues
=> 3.0 beautify README.md

app/Helpers/Request.php
- Add method to access PUT and DELETE parameter and to detect if request is PUT or DELETE request
- improve post() and get() method capabilities to handle access for all POST/GET parameters if no key parameter provided
=> Add method to handle PUT and DELETE HTTP method

app/Config/bootstrap.php, app/Config/config.php, app/Config/constants.php, app/Config/routes.php, app/Core/ClassicRouter.php, app/Modules/Demo/Controllers/Classic.php, app/Templates/Default/Assets/css/style.css, app/Templates/Default/Layouts/default.php, app/Templates/Default/Layouts/themed.php, system/Database/Builder.php, system/Helpers/Number.php, system/Helpers/PhpMailer.php, system/Helpers/Profiler.php, system/Logger.php, system/Net/Request.php, system/Net/Response.php, system/Net/Route.php, system/Net/Router.php, system/Net/Session.php
=> 3.0 - Final Phase, stage continued #2

system/Config.php
Just as the title say.
You can add values to an existing config value (array value).
This will allow modules to add a database link to the database config.
=> Adding add to Config class. To add values to a config value array.

app/Models/Entities/Car.php, app/Modules/Demo/Config/routes.php, app/Modules/Demo/Controllers/Database/Engine.php, app/Modules/Demo/Controllers/Database/Export.php, app/Modules/Demo/Controllers/Database/Service.php, app/Modules/Demo/Controllers/Index.php, app/Modules/Demo/Views/Database/Engine/basicMysql.php, app/Modules/Demo/Views/Database/Engine/basicSqlite.php, app/Modules/Demo/Views/Database/Export/mysql.php, app/Modules/Demo/Views/Database/Service/basicMysql.php, app/Modules/Demo/Views/Database/Service/basicSqlite.php, app/Modules/Demo/Views/Index/home.php, app/Services/Database/Car.php, system/Database/Engine.php, system/Database/Engine/MySQL.php, system/Database/Engine/SQLite.php, system/Database/Service.php
Adding a demo overview, better database demo.
Ready!
=> Renewing Demo with overview & better database demo.

app/Core/ThemedController.php, app/Modules/Demo/Config/config.php, app/Modules/Demo/Controllers/Classic.php, app/Modules/Demo/Controllers/Events.php, app/Modules/Demo/Controllers/Themed.php, app/Modules/Demo/Core/BaseController.php, app/Templates/Default/Assets/css/style.css, app/Templates/Default/Layouts/demos.php, system/Core/View.php
This pull-request implements a complete Theming example and a complete Module classes flow for Demo Module.
@daveismyname Please merge it!
=> 3.0 - Final Phase, stage continued #5

app/Modules/Demo/Config/config.php, app/Modules/Demo/Controllers/Database/Engine.php, app/Modules/Demo/Controllers/Database/Export.php, app/Modules/Demo/Controllers/Database/Service.php, app/Modules/Demo/Controllers/Index.php
Move the Database Demos Controllers on using **\App\Modules\Demo\Core\BaseController** and complete the Demo Module Menu
=> 3.0 - Final Phase, stage continued #6 

app/Modules/Demo/Config/config.php, app/Modules/Demo/Core/BaseController.php, app/Modules/Demo/Language/cs/messages.php, app/Modules/Demo/Language/de/messages.php, app/Modules/Demo/Language/en/messages.php, app/Modules/Demo/Language/es/messages.php, app/Modules/Demo/Language/fr/messages.php, app/Modules/Demo/Language/it/messages.php, app/Modules/Demo/Language/nl/messages.php, app/Modules/Demo/Language/pl/messages.php, app/Modules/Demo/Language/ro/messages.php, app/Modules/Demo/Language/ru/messages.php, app/Templates/Default/Language/cs/messages.php, app/Templates/Default/Language/de/messages.php, app/Templates/Default/Language/en/messages.php, app/Templates/Default/Language/es/messages.php, app/Templates/Default/Language/fr/messages.php, app/Templates/Default/Language/it/messages.php, app/Templates/Default/Language/nl/messages.php, app/Templates/Default/Language/pl/messages.php, app/Templates/Default/Language/ro/messages.php, app/Templates/Default/Language/ru/messages.php
Fix the Dashboard URI in Menu and BaseController from the Module Demo
=> 3.0 - Final Phase, stage continued #7

app/Modules/Demo/Config/config.php, app/Modules/Demo/Config/routes.php, app/Modules/Demo/Core/BaseController.php, app/Templates/Default/Layouts/demos.php
Improve Menu support and adjust Routes on Module Demo
=> 3.0 - Final Phase, stage continued #8 

app/Modules/Demo/Controllers/Database/Engine.php, app/Templates/Default/Layouts/demos.php
Fix URI parsing in Demo Layout from Default Template
=> 3.0 - Final Phase, stage continued #9

.travis.yml, app/Modules/Demo/Controllers/Database/Service.php, app/Modules/Demo/Views/Database/Service/basicMysql.php, app/Modules/Demo/Views/Database/Service/basicSqlite.php
As the title says, fixing the case sensitive service usage in the demo.
=> Fixing service class case sensitivity.

tests/Nova/Database/Service/CarServiceTest.php
Fixing the move in pull request https://github.com/simple-mvc-framework/framework/pull/315
=> Fixing basic service test (moved service Car to demo module).

app/Core/ClassicRouter.php, system/Database/Engine/SQLite.php, system/Net/Router.php
Adding the method \Nova\Net\Router::matchedRoute and make the Callback optionally on default mode; useful for Testing
=> 3.0 - Final Phase, stage continued #11

app/Config/config.php, system/Database/Engine/Base.php, system/Database/Service.php, tests/Nova/Database/Engine/MySQLEngineTest.php, tests/Nova/Database/Engine/SQLiteEngineTest.php
Move to default fetching method PDO::FETCH_ASSOC as optimizing the database server bandwidth and introduce auto-configuration of fetching method in Services.
=> 3.0 - Final Phase, stage continued #14

system/Database/Service.php
Making the Database Services better citizens while auto-configuring the Engine's Fetch Method
=> 3.0 - Final Phase, stage continued #15

app/Config/bootstrap.php, bootstrap.php
=> 3.0 - Final Phase, stage continued #17

app/Config/bootstrap.php, app/Core/BaseModel.php, system/Core/Model.php, system/Database/Engine.php, system/Database/Engine/Base.php
This new **\App\Core\BaseModel** class is an **Extended Model**, which offer useful features like its very own implementation of **Event Observers** and the associated Callbacks, fields protection and so on... :smile: 
Practically, we intend to use this **\App\Core\BaseModel** as a bridge between **Nova  Framework** native&simple **Model** and our in-house Components and APIs.
In other hand, we believe that this **BaseModel** can be very useful for anyone who need a more advanced **Model** than Nova's default one, aka **\Nova\Core\Model**, then its inclusion into **Nova Framework** is well justified.
=> 3.0 - Final Phase, stage continued #18

app/Core/BaseModel.php, system/Database/Engine.php, system/Database/Engine/Base.php
Improve checking of Entity's classPath in **\Nova\Database\Engine\Base**
Small but important change! Please merge it directly!
=> 3.0 - Final Phase, stage continued #20

app/Core/BaseModel.php
Continuing the work in **\App\Core\BaseModel**.
=> 3.0 - Final Phase, stage continued #21

app/Core/BaseModel.php
Completing the 'select', 'select_by' and 'select_all'  methods into **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #22

app/Core/BaseModel.php
Implement the 'order' and 'order_by' methods into **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #23

app/Core/BaseModel.php, system/Core/Model.php
Refactoring of **\App\Core\BaseModel**, on using only the **camelCase** variables and methods and overall optimizations.
The BaseModel lose the ability to use the **snake_case** methods, but its logic is simplified and consolidated.
=> 3.0 - Final Phase, stage continued #24

system/Database/Engine.php, system/Database/Engine/Base.php, system/Database/Service.php, tests/Nova/Database/Engine/MySQLEngineTest.php, tests/Nova/Database/Engine/SQLiteEngineTest.php, tests/Nova/Database/Service/CarServiceTest.php
As the title says, adding updateBatch to engine and service. Also includes tests.
=> 3.0 - Adding updateBatch to engine + service (including tests)

app/Core/BaseModel.php
Consolidate **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #26

app/Core/BaseModel.php
Consolidate (again) **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #27

app/Core/BaseModel.php, app/Modules/Demo/Controllers/Models.php
Improve **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #28

app/Core/BaseModel.php, app/Modules/Demo/Config/config.php
Improve **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #29

app/Core/BaseModel.php, app/Modules/Demo/Controllers/Models.php
Improve the **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #30

app/Core/BaseModel.php, system/Database/Engine.php, system/Database/Engine/Base.php
Implement the 'replace' way methods into **Database Engines** and **BaseModel**
=> 3.0 - Final Phase, stage continued #31

app/Core/BaseModel.php, app/Modules/Demo/Controllers/Models.php
Implement the methods 'countBy' and 'countAll' into **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #32

app/Core/BaseModel.php, system/Helpers/Validator.php
Implementation of **Validation** support into **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #33

app/Core/BaseModel.php
Improve the **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #34

app/Core/BaseModel.php, app/Modules/Demo/Controllers/Models.php, app/Modules/Demo/Language/cs/messages.php, app/Modules/Demo/Language/de/messages.php, app/Modules/Demo/Language/en/messages.php, app/Modules/Demo/Language/es/messages.php, app/Modules/Demo/Language/fr/messages.php, app/Modules/Demo/Language/it/messages.php, app/Modules/Demo/Language/nl/messages.php, app/Modules/Demo/Language/pl/messages.php, app/Modules/Demo/Language/ro/messages.php, app/Modules/Demo/Language/ru/messages.php, system/Database/Engine/Base.php, system/Helpers/Validator.php
Improve **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #35

app/Core/BaseModel.php
Improve **\App\Core\BaseModel**
=> 3.0 - Final Phase, stage continued #36

app/Core/BaseModel.php, system/Core/Model.php
=> Permit to set in the Models constructor a custom Database Engine

LICENSE
=> Happy new year :sparkles:

system/Database/Engine/Base.php, system/Database/Service.php, system/Net/Cookie.php, system/Net/Response.php, system/Net/Router.php, system/Net/Session.php, system/Net/Url.php, tests/Nova/Database/Engine/MySQLEngineTest.php, tests/Nova/Database/Engine/SQLiteEngineTest.php
- Batch Update with multiple where keys. (is optional, could still be a single string!)
- Service will do the multi key with all primary keys.
- Adding escape method to engines.
- Adding tests for rawPrepare, listFields
- Small fixes, improvements
=> 3.0 - Finishing engine, tests etc.

app/Core/BaseModel.php, system/Database/Engine/Base.php
=> Improve error checking into BaseModel and BaseEngine

system/Database/Engine/Base.php
=> Small fix on \Nova\Database\Engine\Base

app/Config/config.example.php, bootstrap.php, composer.json, system/DBAL/Connection.php, system/DBAL/Manager.php, system/Database/Engine/Base.php, system/Database/Engine/SQLite.php, system/ORM/Entity.php
=> 3.0 - Doctrine DBAL based support #1

system/DBAL/Connection.php, system/DBAL/Manager.php
Continue the **\Nova\DBAL** implementation.
=> 3.0 - Doctrine DBAL based support #2

app/Config/config.example.php, app/Modules/Demo/Config/config.php, app/Modules/Demo/Config/routes.php, app/Modules/Demo/Controllers/Doctrine.php, app/Modules/Demo/Views/Doctrine/index.php, bootstrap.php, system/DBAL/Connection.php, system/DBAL/Manager.php, system/Database/Engine/MySQL.php
Complete with Example for **\Nova\DBAL**
=> Adding the Example for \Nova\DBAL

app/Modules/Demo/Config/config.php, app/Modules/Demo/Config/routes.php, app/Modules/Demo/Controllers/Doctrine.php
=> Complete the DBAL Example

system/Cache/ApcCache.php, system/Cache/ApcuCache.php, system/Cache/ArrayCache.php, system/Cache/ChainCache.php, system/Cache/FilesystemCache.php, system/Cache/MemcacheCache.php, system/Cache/MemcachedCache.php, system/Cache/MongoDBCache.php, system/Cache/PhpFileCache.php, system/Cache/PredisCache.php, system/Cache/RedisCache.php, system/Cache/RiakCache.php, system/Cache/Sqlite3Cache.php, system/Cache/VoidCache.php, system/Cache/WinCacheCache.php, system/Cache/XcacheCache.php, system/Cache/ZendDataCache.php
Like the title say; caching support in **17 styles**... :smirk:
=> Adding 17 types of Caching Methods, based on Doctrine Cache

system/Helpers/Collection.php
=> Add the Helper Class: Collection

app/Modules/Demo/Controllers/Doctrine.php, app/Modules/Demo/Controllers/Models.php
=> Add more Queries Examples for DBAL

app/Modules/Demo/Controllers/Doctrine.php
=> Add UPDATE Example for DBAL

app/Modules/Demo/Controllers/Doctrine.php, system/DBAL/Connection.php
=> Add convenience method 'selectAll' and update the DBAL Examples

app/Config/bootstrap.php
Corrected Spelling Mistake
APPPAPTH -> APPPATH
=> Corrected Spelling Mistake in bootstrap.php

.travis.yml, tests/phpunit.xml
=> Continue to clean ROOT

public/index.php, system/Helpers/Collection.php
=> Small changes in Boot file and Collection Helper

system/DBAL/Connection.php
=> Another fix on \Nova\DBAL\Connection::fetchClass

system/DBAL/Connection.php
=> Improving \Nova\DBAL\Connection::select

system/DBAL/Connection.php
=> Improve logic into \Nova\DBAL\Connection

system/ORM/Entity.php
=> Ensure that we set the State in a valid Entity retrieved

system/Net/Filtration/Filter/AbstractFilter.php, system/Net/Filtration/Filter/Callback.php, system/Net/Filtration/FilterFactory.php, system/Net/Filtration/Filtrator.php, system/Validation/Helper.php, system/Validation/Rule/AbstractRule.php, system/Validation/RuleFactory.php
Initial implementation of Sirius based Filtration
=> Initial implementation of Sirius based Data Filtration

system/Input/Element/Factory.php, system/Input/Filter.php
=> Add the Input Filtration and Validation class: \Nova\Input\Filter

app/Core/BaseModel.php
=> Small change into \App\Core\BaseModel

system/Config/bootstrap.php, system/Input/Filter.php
=> Overall small changes

app/Core/BaseModel.php, app/Modules/Demo/Config/config.php, app/Modules/Demo/Controllers/Models.php
Porting of \App\Core\BaseModel to DBAL
=> Porting of \App\Core\BaseModel to DBAL

app/Core/BaseModel.php, app/Modules/Demo/Controllers/Models.php, app/Modules/Demo/Views/Index/home.php
=> Continue porting of \App\Core\BaseModel to DBAL

app/Core/BaseModel.php
=> Small fix into BaseModel

app/Core/BaseModel.php, system/DBAL/Connection.php, system/DBAL/Manager.php
=> Improve \Nova\DBAL and continue porting of \App\Core\BaseModel to DBAL

app/Core/BaseModel.php, system/DBAL/Connection.php, system/DBAL/Manager.php
=> Improve \Nova\DBAL

system/DBAL/Manager.php
=> Improve \Nova\DBAL\Manager

app/Core/BaseModel.php, system/DBAL/Connection.php, system/Helpers/Database.php, system/Helpers/Profiler.php
=> Continue porting of BaseModel to DBAL

system/Language/cs/messages.php, system/Language/de/messages.php, system/Language/en/messages.php, system/Language/es/messages.php, system/Language/fr/messages.php, system/Language/it/messages.php, system/Language/nl/messages.php, system/Language/pl/messages.php, system/Language/ro/messages.php, system/Language/ru/messages.php
=> Update Language files

app/Core/BaseModel.php, app/Modules/Demo/Controllers/Models.php
=> Improve \App\Core\BaseModel

app/Core/BaseModel.php, system/DBAL/Connection.php
=> Improve BaseModel and DBAL

system/Logger.php
=> Update Logger.php - Spelling

system/ORM/Entity.php
- Point added at the end of a sentence, to unify.
- fix typo: "IDs should be an array if primary key values!" => if -> of
=> 3.0 small changes

system/Database/Connection.php, system/Database/QueryBuilder.php, system/Database/TableBuilder.php, tests/Nova/Tests/Database/BuilderTest.php
=> Rename \Nova\Database\Builder as TableBuilder

app/Core/ClassicModel.php, app/Modules/Demo/Controllers/Models/ClassicModel.php, system/Database/Connection.php, system/Database/QueryBuilder.php
Integrate the **\Nova\Database\QueryBuilder** into **\App\Core\ClassicModel**
=> Integrate the \Nova\Database\QueryBuilder into \App\Core\ClassicModel

system/Database/Connection.php
Adjust logic into \Nova\Database\Connection
=> Adjust logic into \Nova\Database\Connection

system/Database/Connection.php, system/ORM/Database.php
Small improvement into error checking.
=> Improve \Nova\Database\Connection and \Nova\ORM\Database

scripts/smvc_members.sql, scripts/testing_mysql.sql, system/Database/Connection.php
And there we go! 
It's about *my favorite* thing: **Fix the Tests**.
@daveismyname BTW, Dave. You really think that you need those Tests who manage to double the work of your programmers, just for fun?
=> Fix the Tests

app/Controllers/Error.php
=> Adjust the \App\Controllers\Error parent to \App\Core\BaseController

app/Config/routes.php, app/Controllers/Error.php
Life is life! So our Error have errors! :smirk:
=> Fix the Error404

app/Packages/DBAL/Connection.php
=> Implement the method fetchArray into \App\Packages\DBAL\Connection

system/ORM/ActiveRecord.php, system/ORM/Connection/Wrapper.php, system/ORM/Expects.php
=> Continue the \Nova\ORM implementation

.travis.yml, app/Core/BaseController.php, app/Core/BaseModel.php, app/Core/ClassicController.php, app/Core/ClassicRouter.php, app/Core/ThemedController.php, public/index.php, scripts/.htaccess, storage/.htaccess, system/Cache/Manager.php, system/Config/functions.php, system/Core/Controller.php, system/Core/Event.php, system/Core/View.php, system/Database/Connection.php, system/Database/Driver/MySQL.php, system/Database/Driver/SQLite.php, system/Database/Manager.php, system/Database/QueryBuilder.php, system/Events/Listener.php, system/Events/Manager.php, system/Input/Filter.php, system/Language.php, system/Logger.php, system/Modules/Manager.php, system/Net/Cookie.php, system/Net/Response.php, system/Net/Route.php
There we go, the big fix pull.
- Changed some stale SMVC to Nova
- Fixing syntax error in CacheManager
- Fixing missing import bug in CacheManager
- Fixing Logger sendEmail, was still using old PhpMailer syntax.
- Adding several phpdocs for a lot of methods
- Can still be not correct, if not please correct me after this pull request. I can't be accurate for 100%.
- Untouched: The Nova Small ORM (still in building phase), Helpers, Input and Validator (needs more checking)
There is a bug in the Connection.php, it's been marked as unstable in the phpdoc and marked with TODO at the line of the bug.
@LuckyCyborg Please look into this, I don't know exactly what you wanted to do in this line so I didn't fix it. Please open pull to fix later.
Maybe the doc style I use here isn't your style. …
=> 3.0 - Lots of bugfixes!! And PHPDoc!!

system/Cache/Manager.php
=> Fix \Nova\Cache\Manager

system/ORM/Model.php, system/ORM/Relation/Joining/Pivot.php
=> Improve \Nova\ORM\Relation\Joining\Pivot

app/Modules/Demo/Controllers/Models/RelationalModel.php, system/ORM/Builder.php, system/ORM/Model.php, system/ORM/Relation.php, system/ORM/Relation/BelongsTo.php, system/ORM/Relation/BelongsToMany.php, system/ORM/Relation/HasMany.php, system/ORM/Relation/HasOne.php, system/ORM/Relation/Pivot.php
This PULL introduce into **Nova\ORM** an improved Relations management, notably into **belongsToMany** Relation; also being enhanced the **Nova\ORM\Builder**.
=> Improve Nova\ORM

app/Helpers/Date.php
return current month's number of days if $month is lesser than 1 or bigger than 12.
=> return current month' days

nova/system/Core/routes.php
=>  Small cleanup into nova/system/Core/routes.php

nova/app/Controllers/Welcome.php, nova/system/Core/routes.php, public_html/.htaccess
There is no such thing like **lang** session right now, then the **Language** helper fail to load the proper file.
So, that patch will fix the problem described into my latest post.
All the best!
=> Fix the Routing & Co.

app/Core/Language.php
This will allow loading more than one language. Also it allows the use of a different language for same term when retrieving it.
=> allow loading and retrieval of multiple language terms

app/Helpers/Url.php
=> add server status code for redirect

nova/system/Core/ClassicRouter.php, nova/system/Core/Router.php
This PR consolidate the Routing behavior when are used the Routes which use the Closures, returning the result of Closure execution, similar with execution of Controller's Methods.
=> Consolidate the Core\Router behavior in the case of Routes with Closure

nova/system/Core/ClassicRouter.php, nova/system/Core/Router.php
Like the title say, this PR consolidate the Routing behavior and nothing is changed as end-user interface.
=> Consolidate the Core\Router and Core\ClassicRouter behaviour

README.md
Changed Helper Classes link to reflect new location.
=> Changed 'Helper Classes' link

system/Helpers/Url.php
This PR improve the URI detection into **Url::detectUri()** and fix the Issue #700
=> Improve the URI detection and fix #700

system/bootstrap.php
@daveismyname Okay, then a small additional PR, to improve the bootstrap order of commands...
=> Improve bootstrap stage order

system/Helpers/Cookie.php
Like title say, this PR improve the **Helpers\Cookie** behavior and make it to properly delete the Cookies.
=> Fix the the behavior of the method 'destroy' into Helpers\Cookie

app/Language/Cs/Welcome.php, app/Language/De/Welcome.php, app/Language/Fr/Welcome.php, app/Language/It/Welcome.php, app/Language/Nl/Welcome.php, app/Language/Pl/Welcome.php, app/Language/Ro/Welcome.php, app/Language/Ru/Welcome.php
=> Fix the Views path into Language files

.gitignore, system/Core/Controller.php, system/Core/Router.php, system/Core/View.php
This pull request introduce a new composite method into Core\View, capable to fetch the View rendering and able to work also with Modules. Its usage is simple:
```php
$content = View::fetch('Page/Show', $data, 'Pages');
echo $content;
```
OR
```php
$data['content'] = View::fetch('Welcome/SubPage', $data);
View::renderTemplate('default', $data);
```
To note that the third parameter of the View::fetch() is an optional Module name, permitting a style similar with View::renderTemplate(), without specifying the full path into Module.
Using this new method permit even to use an alternative rendering style, using Layouts.
In other hand, this pull-request introduce a simple and non-invasive post-processing support into Controllers execution, having a new Method, called 'after', which is …
=> Improve the Routing, Controllers and View rendering

app/Language/Es/Welcome.php
=> Spanish language added

system/Core/Controller.php
Adjust **Core\Controller@after** to correct handle the standalone View/Template instance handling.
=> Consolidate Core\Controller

app/Language/Fa/Welcome.php, app/Templates/Default/header.php
adding persiang language to nova-framework
=> Add Persian Language

system/Core/Template.php
=> Small change into Core\Template to fix the work on some PHP versions

system/Helpers/Encrypter.php
=> Added Encrypter helper

app/Config.example.php, app/Controllers/Auth.php, app/Controllers/Dashboard.php, app/Controllers/Demo.php, app/Filters.php, app/Routes.php, app/Templates/Default/custom.php, app/Templates/Default/default.php, app/Views/Auth/Login.php, app/Views/Dashboard/Index.php, app/Views/Error/400.php, scripts/nova_users.sql, system/Auth/Auth.php, system/Auth/Guard.php, system/Auth/Model.php, system/Core/Aliases.php, system/Database/Connection.php, system/Database/JoinClause.php, system/Database/Model.php, system/Database/Query.php, system/Helpers/Csrf.php, system/Helpers/Encrypter.php, system/bootstrap.php
This pull-request introduce a simple but efficient **Auth** system, in a Laravel-esque style.
All the classes of that **Auth** system live in the namespace **\Auth\** and is implemented also a reference structure for User Authentication in the **\App\** namespace.
To note that additional **Route Filters** are added, to support this reference implementation and the properly configuration of **Helpers\Encrypter**, as in valid **ENCRYPT_KEY**, is required.
Being an **Users Management**, of course, a Database is required and in **scripts/nova_users.sql** you can find the associated MySQL dump for the **users** Table. 
Important: as Database API is used the new one, living in the namespace **\Database\**, then if you choose to use this Auth System, you should use that new Database API in the …
=> Implementation of a simple Auth system

app/Controllers/Auth.php, system/Auth/Guard.php
=> Improve App\Controllers\Auth and fix comment typo on Auth\Guard

app/Config.example.php
=> Small fix into app/Config.example.php

app/Config.example.php
Add the missing option for the Auth configuration.
=> Adjust the Auth configuration

app/Controllers/Users.php, app/Models/Users.php, system/Core/View.php, system/Database/JoinClause.php, system/Database/Model.php, system/Database/Query.php
Like title say, this is a small pull-request which remove the **View::renderModule()** associated Exception throwing and do some assorted optimizations.
=> Remove the View::renderModule() associated Exception throwing and assorted optimizations

app/Controllers/Users.php, app/Filters.php, app/Routes.php, system/Auth/Auth.php, system/Auth/Guard.php, system/Auth/Model.php
This pull request introduce a new **Auth\Guard** method, which check the User state as **guest** with a very simple usage:
```php
if(Auth::guest()) {
// Do something, the User is not logged in.
}
```
Also, there are introduced optimizations of **Auth System** and a fix into **App\Controllers\Users@profile**.
=> Improve the Auth System

app/Controllers/Users.php, app/Views/Users/Profile.php
This pull request contains a small improvement on **App\Constrollers\Users@profile**, showing the User Name into page title.
=> Improve User Profile

system/Database/Model.php
=> Try to auto-configure the Table into Database\Model only in the child Classes

app/Templates/Default/message.php, system/Database/Connection.php, system/Database/Query.php, system/Helpers/Session.php
Improve the **Helpers\Session@message** and make the generated messages to be rendered in a Templated way.
=> Improve the Helpers\Session@message and make the messages Templated

system/Core/Error.php, system/Database/Facade.php
=> Improve Core\Error

system/Auth/Guard.php, system/Core/Base/Router.php, system/functions.php
=> Improve Auth\Guard and introduce a strong random string generator called str_random()

system/Core/Aliases.php
As it would be nice to know which class already exists with the same name.
=> Added the class alias in the RuntimeException message.

app/Modules/Users/Controllers/Users.php, app/Modules/Users/Language/Cs/messages.php, app/Modules/Users/Language/De/messages.php, app/Modules/Users/Language/En/messages.php, app/Modules/Users/Language/Es/messages.php, app/Modules/Users/Language/Fa/messages.php, app/Modules/Users/Language/Fr/messages.php, app/Modules/Users/Language/It/messages.php, app/Modules/Users/Language/Ja/messages.php, app/Modules/Users/Language/Nl/messages.php, app/Modules/Users/Language/Pl/messages.php, app/Modules/Users/Language/Ro/messages.php, app/Modules/Users/Language/Ru/messages.php, system/Database/Connection.php, system/Database/Model.php, system/Database/ORM/Model.php, system/Database/Query/Builder.php, system/Database/Query/JoinClause.php, system/Validation/Facade.php, system/Validation/Translator.php
=> Assorted optimizations and fixes

app/Controllers/Language.php, system/Core/Language.php
=> Optimize the Language System.

system/Core/Logger.php
Add setter for display value.
Now u can use Logger::setDisplay(true); in Config file to show errors on page, not only in logfile
=> Add display setter

app/Config.example.php, app/Language/Ro/Welcome.php, app/Modules/Users/Controllers/Users.php, app/Templates/Default/default.php, app/Templates/Default/header.php, system/Core/ClassicRouter.php, system/Core/Language.php, system/Core/Request.php, system/Core/Router.php, system/Helpers/Request.php, system/Support/Facades/Language.php, system/functions.php
This pull request introduce optimizations on Language System and add a dedicated Facade to, solution giving the ability to simplify the logic of the **Core\Language**.
Also, is improved the displaying of Language Changer on Default Template, now indicating the current Language.
Finally, this pull request introduce improvements into **Helpers\Request**, as in adding support for the **HEAD**, **PUT**, **DELETE** and **OPTIONS** methods, for a enhanced **RESTful** APIs experience; also moving it to **Core\Request** as being a vital part of the Framework and not a (optional) Helper.
To note that this pull request do **not** introduce any API breaks.
=> Improve the Request and Language System, introduce the Support\Facades\Language

app/Templates/Default/default-rtl.php, app/Templates/Default/header-rtl.php, system/Core/Request.php, system/Core/Template.php
To note that pull request contains a **HOT-FIX** about synchronizing the previous merged commits with the new Language API.
=> Synchronize the Layouts and Core\Template with the new Language API

system/Core/Language.php, system/Core/Request.php, system/Support/Facades/Language.php, system/Validation/Factory.php, system/Validation/Validator.php, system/functions.php
To note that also this pull request improve the **Language System**.
=> Improve the Language System and the compatibility with PHP7 on Validation\Factory and Validation\Validator

system/Http/Response.php
=> Fix typo on Http\Response

nova, system/Cli/EncryptionCommand.php
use 
````php
php nova make:key
```
in your console, to generate a key for the config file.
=> Add: Encryption Key generation to the CLI.

system/functions.php
=> Add array_only to system/functions.php

system/Database/Model.php, system/Database/ORM/Model.php, system/functions.php
This pull request introduce a basic CRUD support on **Database\Model**, via a small set of common used Methods. Usage for the following Model:
```php
<?php
namespace App\Models;
use Database\Model;
class Users extends Model
{
protected $table = 'users';
protected $primaryKey = 'id';
}
```
Create a Model instance and get all registered Users
```php
$model = new \App\Models\Users();
$users = $model->all();
// Do something with the Users list
```
Find and get a User Record
```php
$user = $model->find(1);
// Do something with the User object
```
Delete a User Record
```php
$model->delete(1);
```
Update a User Record
```php
$data = array(
'email' => 'daniel@novaframework.dev'
);
$model->update(1, $data);
```
Insert a new User Record and return its ID
```php
$data = array(
'username' => …
```
=> Introducing a basic CRUD support on Database\Model

system/Database/Model.php
=> Fix Database\Model@all

composer.json, system/Helpers/FastCache.php
=> Upgrade the used PhpFastCache (by Helpers\FastCache) to version 4.x

system/Core/Controller.php, system/Core/Template.php
Like the title say, this pull request improve the logic on **Improve Core\Template@make**
=> Improve Core\Template@make

app/Config/Database.php, system/Database/Connection.php, system/Database/Connectors/Connector.php, system/Database/Connectors/ConnectorInterface.php, system/Database/Connectors/MySqlConnector.php, system/Database/Connectors/PostgresConnector.php, system/Database/Connectors/SQLiteConnector.php, system/Database/Query/Builder.php
This pull request introduce in the **Database API** the support for using **PostgresSQL** and **SQLite** Databases also, behind of the **MySQL** ones.
**To note that this pull request does NOT introduce any API changes of breaks.**
=> Introduce in the Database API the support for using PostgresSQL and SQLite Databases

app/Config.example.php, app/Modules/Users/Controllers/Reminders.php, app/Modules/Users/Controllers/Users.php, app/Modules/Users/Language/Cz/messages.php, app/Modules/Users/Language/Da/messages.php, app/Modules/Users/Language/De/messages.php, app/Modules/Users/Language/En/messages.php, app/Modules/Users/Language/Es/messages.php, app/Modules/Users/Language/Fa/messages.php, app/Modules/Users/Language/Fr/messages.php, app/Modules/Users/Language/It/messages.php, app/Modules/Users/Language/Ja/messages.php, app/Modules/Users/Language/Nl/messages.php, app/Modules/Users/Language/Pl/messages.php, app/Modules/Users/Language/Ro/messages.php, app/Modules/Users/Language/Ru/messages.php, app/Modules/Users/Views/Reminders/Remind.php, app/Modules/Users/Views/Users/Login.php, system/Helpers/ReCaptcha.php
=> Complete the integration of Google ReCaptcha on Users Module

app/Modules/Users/Controllers/Reminders.php, app/Modules/Users/Views/Reminders/Reset.php
=> Add Google reCAPTCHA check for the Pasword Reset on Users module

system/Cli/ControllerCommand.php, system/Database/Query/Builder.php, system/Pagination/BootstrapPresenter.php
=> Add method Database\Query\Builder@addSelect, being required by ORM for May-to-Many relations

README.md
=> Removed BSD-3 License Badge

app/Templates/AdminLte/Language/Cz/messages.php, app/Templates/AdminLte/Language/Da/messages.php, app/Templates/AdminLte/Language/De/messages.php, app/Templates/AdminLte/Language/En/messages.php, app/Templates/AdminLte/Language/Es/messages.php, app/Templates/AdminLte/Language/Fa/messages.php, app/Templates/AdminLte/Language/Fr/messages.php, app/Templates/AdminLte/Language/It/messages.php, app/Templates/AdminLte/Language/Ja/messages.php, app/Templates/AdminLte/Language/Nl/messages.php, app/Templates/AdminLte/Language/Pl/messages.php, app/Templates/AdminLte/Language/Ro/messages.php, app/Templates/AdminLte/Language/Ru/messages.php, app/Templates/AdminLte/Language/cs/messages.php, app/Templates/AdminLte/Language/de/messages.php, app/Templates/AdminLte/Language/en/messages.php, app/Templates/AdminLte/Language/es/messages.php, app/Templates/AdminLte/Language/fr/messages.php, app/Templates/AdminLte/Language/it/messages.php, app/Templates/AdminLte/Language/nl/messages.php, app/Templates/AdminLte/Language/pl/messages.php, app/Templates/AdminLte/Language/ro/messages.php, app/Templates/AdminLte/Language/ru/messages.php
=> Adjust the Langauge files on the AdminLte Template

app/Templates/AdminLte/custom.php
=> Adjust the images laoding on Custom Layout from AdminLte Template

app/Modules/Users/Controllers/Users.php
=> Hot fix for changing password on App\Modules\Users\Controllers\Users

app/Modules/Users/Controllers/Authorize.php, app/Modules/Users/Controllers/Users.php, app/Modules/Users/Views/Authorize/Login.php, app/Modules/Users/Views/Authorize/Remind.php, app/Modules/Users/Views/Authorize/Reset.php, app/Modules/Users/Views/Users/Dashboard.php, app/Modules/Users/Views/Users/Profile.php, app/Templates/AdminLte/backend.php, app/Templates/Default/message.php, system/Http/RedirectResponse.php, system/Support/Facades/Session.php
This pull request introduce diverse improvements, small updates on **Users** module another optimizations.
First of all, a utility method called **withStatus()** is introduced on **Http\RedirectResponse**, which simplify the work with the passing message on new pages, generating a correct New Style Message for **\Support\Facades\Session@message**. Usage is simplified:
```php
public function store()
{
// Validate the Input data.
$input = Input::only('name', 'category', 'hours', 'cfu');
$validator = $this->validate($input);
if($validator->passes()) {
// Process the Input data there.
...
// Prepare the flash message.
$status = __('The Course <b>{0}</b> was successfully created.', $course->name);
return Redirect::to('admin/courses')->withStatus($status);
}
// Errors occurred on Validation. …
```
=> Overall (but small) improvements

app/Modules/Dashboard/Controllers/Admin/Dashboard.php
=> Small fix on App\Modules\Dashboard\Controllers\Admin\Dashboard@before

app/Modules/Users/Views/Admin/Users/Create.php
=> Fix the User creation on Users module

app/Filters.php, system/Auth/Guard.php, system/Routing/ClassicRouter.php, system/Routing/Route.php, system/Routing/Router.php
This pull request introduce a series of optimizations on **Routing**, and some improvements which enhance the abilities of the end-user to control the Routing behavior.
The notable improvements are the ability to pass custom data to a **Route** and the **Route Filters** definition also as a array, i.e.
```php
Router::post('login', array(
'filters' => array('guest', 'csrf'),
'uses' => 'App\Modules\Users\Controllers\Authorize@postLogin'
));
```
As example for passing custom data to a Route could be, in future:
```php
Route::get('admin/shiny-things/(:any)', array(
'filters' => array('auth', 'roles'), // A 'roles' Filter must be specified
'uses' => 'App\Controllers\Admin\ShinyThings@index',
'roles' => array('administrator', 'manager') // Only an administrator, or a manager can access this …
```
=> Optimizations and improvements on Routing

app/Modules/Dashboard/Views/Admin/Dashboard/Index.php, app/Modules/Users/Controllers/Admin/Users.php, app/Modules/Users/Views/Admin/Roles/Create.php, app/Modules/Users/Views/Admin/Roles/Edit.php, app/Modules/Users/Views/Admin/Roles/Index.php, app/Modules/Users/Views/Admin/Roles/Show.php, app/Modules/Users/Views/Admin/Users/Create.php, app/Modules/Users/Views/Admin/Users/Edit.php, app/Modules/Users/Views/Admin/Users/Index.php, app/Modules/Users/Views/Admin/Users/Profile.php, app/Modules/Users/Views/Admin/Users/Search.php, app/Modules/Users/Views/Admin/Users/Show.php, app/Modules/Users/Views/Authorize/Login.php, app/Modules/Users/Views/Authorize/Remind.php, app/Modules/Users/Views/Authorize/Reset.php, system/Http/RedirectResponse.php, system/Support/Facades/Session.php
=> Improve the flash Messages management and fixes on Users module

app/Templates/AdminLte/backend.php
Small improvement on Backend Layout on AdminLTE Template.
=> Improve the Backend Layout on AdminLTE Template

app/Config.example.php, app/Templates/AdminLte/backend.php, app/Templates/AdminLte/default.php, app/Templates/Default/custom-rtl.php, app/Templates/Default/custom.php, app/Templates/Default/default-rtl.php, app/Templates/Default/default.php, app/Templates/Default/footer-rtl.php, app/Templates/Default/footer.php
=> Add the VERSION definition, reading the root file VERSION.txt

app/Templates/AdminLte/backend.php, app/Templates/AdminLte/default.php
=> Add a Language Changer to the AdminLTE Template's Layouts

app/Templates/AdminLte/backend.php, app/Templates/AdminLte/default.php
=> Improve the Language Changer on the Layouts from AdminLTE Template

app/Config/App.php, app/Modules/Dashboard/Views/Admin/Dashboard/Index.php, app/Modules/Settings/Controllers/Admin/Settings.php, app/Modules/Users/Controllers/Admin/Users.php, app/Modules/Users/Controllers/Registrar.php, app/Modules/Users/Helpers/RoleVerifier.php, app/Templates/AdminLte/backend.php, app/Templates/AdminLte/default.php, app/Templates/Default/custom-rtl.php, app/Templates/Default/custom.php, app/Templates/Default/default-rtl.php, app/Templates/Default/default.php, app/Templates/Default/footer-rtl.php, app/Templates/Default/footer.php, system/Core/Aliases.php, system/Core/Application.php, system/Core/Controller.php, system/Routing/Redirector.php, system/Routing/Route.php, system/Session/DatabaseSessionHandler.php, system/Session/FileSessionHandler.php, system/Support/Facades/App.php
This pull request introduce a improvement in Middleware, now correctly processing the case when the **before()** stage return a Response or Redirect instance.
Also, in the **App\Users\Controllers\Admin\Users** is adjusted the Middleware, to permit to any User, behind its Role,  the access to its **Profile**.
Finally, are introduced some fixes, on some alternative Framework's components and is updated **app/Config/App.php**
=> Improved Middleware, fixes on demo Modules and non-critical components, and defining the usual Services on app/Config/App.php

app/Config/App.php, system/Auth/AuthManager.php, system/Auth/AuthServiceProvider.php, system/Auth/Reminders/PasswordBroker.php, system/Auth/Reminders/ReminderRepository.php, system/Auth/Reminders/ReminderRepositoryInterface.php, system/Auth/Reminders/ReminderServiceProvider.php, system/Cookie/CookieServiceProvider.php, system/Database/DatabaseManager.php, system/Database/DatabaseServiceProvider.php, system/Encryption/EncryptionServiceProvider.php, system/Hashing/BcryptHasher.php, system/Hashing/HashServiceProvider.php, system/Hashing/HasherInterface.php, system/Mail/MailServiceProvider.php, system/Pagination/PaginationServiceProvider.php, system/Routing/RoutingServiceProvider.php, system/Session/SessionServiceProvider.php, system/Support/Manager.php, system/Validation/ValidationServiceProvider.php
=> Improve Auth\Reminders and add the infrastructure of the Service Providers

app/Config.example.php, app/Config/App.php, app/Config/Cache.php, app/Config/Session.php, system/Database/Connection.php
This pull request improve and simplify the Framework configuration and introduce some small changes on **Database\Connection**.
To note that it could qualify for a micro-release and introduce **no API changes**.
=> Improve the Framework configuration and small changes on Database\Connection

app/Boot/Start.php, system/Database/DatabaseManager.php, system/Exception/HttpExceptionDisplayer.php, system/Exception/JsonExceptionDisplayer.php, system/Foundation/AliasLoader.php, system/Foundation/Application.php, system/Foundation/EnvironmentDetector.php, system/Foundation/ProviderRepository.php, system/Http/RequestProcessor.php, system/Http/ResponseProcessor.php, system/Routing/Router.php, system/Support/Facades/Facade.php, system/Support/Manager.php, system/Support/ServiceProvider.php
=> Improve Exception displayers and move the kernel classes to namespace \Foundation

system/bootstrap.php
=> Fix system/bootstrap.php

app/Controllers/Demo.php, system/Database/DatabaseServiceProvider.php, system/Database/Model.php, system/Helpers/Database.php
=> Improve the Helpers\Database and integrate it on Database Service

system/Config/DatabaseLoader.php
Like the title say, internal API change only.
=> Disable caching support on Config API when ENVIRONMENT is equal with 'development'

app/Templates/AdminLte/backend.php, system/Database/Query/Builder.php, system/Pagination/Factory.php
=> Fix the New Style Pagination

app/Templates/AdminLte/Language/Cz/messages.php, app/Templates/AdminLte/Language/Da/messages.php, app/Templates/AdminLte/Language/De/messages.php, app/Templates/AdminLte/Language/En/messages.php, app/Templates/AdminLte/Language/Es/messages.php, app/Templates/AdminLte/Language/Fa/messages.php, app/Templates/AdminLte/Language/Fr/messages.php, app/Templates/AdminLte/Language/It/messages.php, app/Templates/AdminLte/Language/Ja/messages.php, app/Templates/AdminLte/Language/Nl/messages.php, app/Templates/AdminLte/Language/Pl/messages.php, app/Templates/AdminLte/Language/Ro/messages.php, app/Templates/AdminLte/Language/Ru/messages.php, app/Templates/AdminLte/backend-rtl.php, app/Templates/AdminLte/backend.php, app/Templates/AdminLte/default-rtl.php, app/Templates/AdminLte/default.php, system/Routing/Router.php
On this pull request are adjusted the translation calls on the **AdminLTE** Template and updated its Language files.
Also, there is introduced a small fix about Assets Serving from Modules, on the Routing: **Routing\Router@dispatchFile**.
=> Improve the Routing Asset Serving and the AdminLTE Template

system/Routing/Route.php
This is a small bug-fix of **Routing\Route@getAction**.
=> Fix the Routing\Route@getAction

app/Modules/Users/Helpers/RoleVerifier.php, system/Database/Model.php, system/Database/Query.php, system/Database/Query/Builder.php
This pull-request introduce a improvement of **Database\Model** and add a dedicated **QueryBuilder** for it, in the same time simplifying and consolidating the **Database\Query\Builder**.
To note that the code represent a back-porting of the related optimizations present on **Nova 4** and basically does not introduce API changes, then it could qualify for a micro version increase.
=> Improve Database\Model and add a (dedicated) QueryBuilder for it

system/Database/Model.php, system/Database/Query.php
This pull request add to **Database\Model** the method **findMany()** (introduced on the last pull-request on its associated **QueryBuilder**) and simplify the method **find()**.
To note that this is another small back-port from Nova 4.
=> Improve Database\Model

system/functions.php
=> Improve the function class_basename from system/functions.php

system/Core/Controller.php, system/Core/View.php
This pull-request improve the **Core\Controller** Execution Flow, optimizing it to complete execute the Controller **Middleware**, even when the the Action execution is skipped because a Before Stage decision.
Also, are introduced improvements on the Legacy Views Rendering support and the additional processing for automatically calculate the View file associated with the current Action is moved to **getView()**, from speed optimization reasons. 
To note that there are introduced **no changes** on Controller's Public API.
=> Improve Core\Controller

app/Config/Session.php, system/Routing/Router.php, system/Session/CookieSessionHandler.php, system/Session/DatabaseSessionHandler.php, system/Session/ExistenceAwareInterface.php, system/Session/Store.php
=> Fix the behavior when using the Route::resource() commands and Database based Sessions

app/Boot/Global.php, app/Config/App.php, app/Templates/Default/header-rtl.php, app/Templates/Default/header.php, app/Views/Error/404.php, system/Foundation/Application.php, system/Routing/AssetFileDispatcher.php, system/Routing/Route.php, system/Routing/RouteCollection.php, system/Routing/Router.php
Like the title say, this pull request Implement a Route Collection and matching them per HTTP Method.
In other hand, the Routing is overall consolidated.
The advantage is that number of checked Routes on a Request dispatching will be reduced, being checked only ones assigned for the current HTTP Method, and adding a major speed-up specially on RESTful APIs, but not only.
BTW, No API Changes.
=> Implementation of Route Collection and matching them per HTTP Method

system/Pagination/Presenter.php
=> Fix the behavior on Pagination\Presenter

system/Database/Query.php, system/Routing/Router.php
=> Fix the behaviour of pagination on Database\Query and improve Routing\Router@invokeCallback

system/Routing/ControllerDispatcher.php, system/Routing/Route.php, system/Routing/RouteFiltererInterface.php, system/Routing/Router.php
This pull request consolidate the Routing, and his strong point is introducing the **Dependency Injection** on created Controller instances, which are made via **Foundation\Application** container.
No API changes, good for a micro release.
=> Consolidate the Routing

app/Routes.php, system/Routing/Router.php
=>  Improve the Routing

app/Config/App.php, app/Controllers/Welcome.php, system/Routing/Route.php, system/Routing/Router.php, system/functions.php
Yup! I nuke from orbit this filthy thing. So the Lazy Guys should move their ass and do some real codding if they want multilingual sites. 
To note that I made a multilingual site on SMVC 2.1, without asking @daveismyname to patch the Framework for.
=> Remove the Multilingual Support

system/Routing/AssetFileDispatcher.php
=> Improve Routing\AssetFileDispatcher

system/Routing/AssetFileDispatcher.php
=> Permit the HEAD method on Asset Files Serving via Routing

system/Routing/FileDispatcher.php, system/Routing/Router.php
No API Changes; good for a micro version release.
=> Consolidate the Asset Files Serving and move Routing\AssetFileDispatcher to Routing\FileDispatcher

system/Http/JsonResponse.php, system/Http/RedirectResponse.php, system/Http/Request.php, system/Http/Response.php, system/Http/ResponseTrait.php
This pull request consolidate the **Http API**.
No API Changes, good for a micro version release.
=> Consolidate Http API

app/Language/Cz/messages.php, app/Language/Ru/messages.php
=> Update the Czech and Russian Language

app/Config/Routing.php, app/Controllers/Demo.php, system/Routing/ControllerInspector.php, system/Routing/Route.php, system/Routing/Router.php
=> Consolidate the Routing and its Smart Pattern Compilers

app/Controllers/Demo.php, app/Modules/Dashboard/Routes.php, system/Routing/Route.php, system/Routing/RouteCompiler.php, system/Routing/Router.php
This pull-request add some useful methods to **Routing\Route** and reorganize its code.
=> Improve Routing\Route

system/Routing/Route.php
=> Improve the Route pattern prefixing on Routing\Route@prefix

system/Routing/Route.php, system/Routing/RouteCompiler.php
=> Hot fix - improve the processing of empty patterns, prefixed or not

system/Core/BaseView.php
=> Adjust Core\BaseView@display to work on new the Nova environment

app/Modules/Files/Config.php, app/Modules/Files/Controllers/Admin/Files.php, app/Modules/Files/Routes.php, app/Modules/Files/Views/Admin/Files/Connector.php, system/Routing/FileDispatcher.php
Like the title say, some small fixes and improvements on **Files** Module.
=> Improve the Files Module

app/Modules/Files/Views/Admin/Files/Index.php, app/Templates/AdminLte/backend.php, app/Templates/AdminLte/default.php, app/Templates/Default/custom-rtl.php, app/Templates/Default/custom.php, app/Templates/Default/default-rtl.php, app/Templates/Default/default.php, app/Templates/Default/header-rtl.php, app/Templates/Default/header.php
=> Proper apply the Language settings on Templates and elFinder setup from Files Module

app/Boot/Global.php
Like the title say, this pull error fix the... errors. Good for a micro version release.
=> Adjust Application's Missing Handler to be json compatible - fix #1084

app/Core/Controller.php, app/Events.php, app/Extensions/Http/ContentGuard.php, app/Filters.php, system/Core/Controller.php, system/Template/Factory.php, system/Template/Template.php, system/View/Engines/EngineInterface.php, system/View/Engines/PhpEngine.php, system/View/View.php
This pull request introduce some small improvements on **Core\Controller** and **Template\Factory**.
**No API changes**, good for a micro version release.
=> Improve the Core\Controller and Template\Factory

app/Core/BackendController.php, app/Core/Controller.php, app/Legacy/Controller.php, system/Forensics/Profiler.php, system/Helpers/Database.php, system/Helpers/Profiler.php, system/Helpers/ReCaptcha.php, system/Redis/RedisServiceProvider.php, system/Session/ExistenceAwareInterface.php, system/Session/Store.php, system/Support/Facades/Response.php
This pull request consolidate the compatibility with some PHP versions, using directly the required Facades on the Framework System.
**No API changes**, good for a micro version release.
=> Use directly the required Facades on the Framework System

app/Boot/Environment/Local.php, app/Boot/Global.php, app/Boot/Start.php, app/Config/App.php, app/Core/Controller.php, app/Modules/Demos/Controllers/Demos.php, system/Database/Query/Expression.php, system/Database/Query/JoinClause.php, system/Exception/Handler.php, system/Foundation/Application.php, system/Routing/Matching/MethodValidator.php, system/Routing/Matching/SchemeValidator.php, system/Routing/Matching/UriValidator.php, system/Routing/Matching/ValidatorInterface.php, system/Routing/Redirector.php, system/Routing/Route.php, system/Routing/RouteCollection.php, system/Routing/RouteCompiler.php, system/Routing/RoutingServiceProvider.php, system/Routing/UrlGenerator.php, system/Support/Facades/Language.php, system/Template/Factory.php, system/Template/Template.php, system/View/View.php, system/View/ViewServiceProvider.php
No APIs change, good for a micro version release.
=> Improve the Language management and App\Core\Controller

system/Database/Query/Builder.php, system/Events/Dispatcher.php, system/Foundation/EnvironmentDetector.php, system/Http/RedirectResponse.php, system/Routing/Matching/SchemeValidator.php, system/Routing/UrlGenerator.php
=> Improve Routing\UrlGenerator

app/Modules/Demos/Controllers/Demos.php, system/Auth/Reminders/ReminderServiceProvider.php, system/Routing/CompiledRoute.php, system/Routing/Matching/HostValidator.php, system/Routing/Route.php, system/Routing/RouteCollection.php, system/Routing/RouteCompiler.php, system/Routing/UrlGenerator.php
=> Improve the Routing and adjust the Auth\Reminders\ReminderServiceProvider

app/Modules/Demos/Controllers/Demos.php, app/Storage/Logs/error.log, system/Exception/SymfonyDisplayer.php, system/Routing/Compiler/CompiledRoute.php, system/Routing/Compiler/RouteCompiler.php, system/Routing/Compiler/RouteCompilerInterface.php, system/Routing/Route.php
=> Improve the Routing - a better Route compilation

system/Routing/Legacy/RouteParser.php, system/Routing/Route.php
This pull request consolidate and fix the handling of the optional parameters on Routing, on both styles.
=> Fix the handling of the optional parameters on Routing

app/Filters.php
=> Routing - Improve the User Authorization FIlters

app/Filters.php
=> Hot Fix: adjust the CSRF Token Name on the Route Filter

app/Core/Controller.php, system/Language/LanguageServiceProvider.php, system/Support/Facades/Session.php, system/Template/Factory.php, system/View/Factory.php
=> Overall improvements and fine tuning

app/Modules/System/Controllers/Admin/Settings.php
=> Improve the App\Modules\System\Controllers\Admin\Settings@index

system/Helpers/Profiler.php, system/Language/Cs/messages.php, system/Language/Da/messages.php, system/Language/De/messages.php, system/Language/En/messages.php, system/Language/Es/messages.php, system/Language/Fa/messages.php, system/Language/Fr/messages.php, system/Language/It/messages.php, system/Language/Ja/messages.php, system/Language/Nl/messages.php, system/Language/Pl/messages.php, system/Language/Ro/messages.php, system/Language/Ru/messages.php, system/Routing/ControllerInspector.php
=> Improve the Helpers\Profiler

app/Filters.php, app/Modules/System/Controllers/Authorize.php, system/Foundation/Application.php, system/Routing/Assets/DefaultDispatcher.php, system/Session/Middleware.php, system/View/Factory.php
Use the `Redirect::intended()` on `App\Modules\System\Controllers\Authorize@postLogin`
Honor the Modules path configuration on **Assets Dispatching** and **View Factory**.
=> Overall improvements

app/Core/Controller.php
=> Honor the Modules configuration on App\Core\Controller@getView

composer.json
=> Update the composer.json

app/Config.php
=> Update the Routing configuration to match the improved Assets Dispatching from the Nova System

app/Filters.php, app/Modules/System/Filters.php
To note that the User Roles filter is moved to System Module, as NOT being an essential component for Application, but a pure example of implementation of User Role based filtering and even the example Backend, made by the shipped modules, use another filtering solution, which I consider better on this case.
=> Adjust the User Roles filter

app/Boot/Start.php, app/Modules/Files/Views/Admin/Files/Index.php
=> Improve app/Boot/Start.php

app/Core/BackendController.php
=> Consolidate App\Core\BackendController

app/Boot/Global.php
=> [3.0] Improve the HTTP Exceptions handling
