app/Core/View.php
People might put $custom on 0, "0" or "false"
Let's make sure they don't fool the system
=> Make $custom fool-proof

app/Helpers/Csrf.php, app/Helpers/Request.php
The current implementation of CSRF tokens can be enhanced:
1 . The current implementation is per-form; means if you have multiple opened pages from your website, and each page has a form, you will ending up having different tokens in each form.
+ This could result in invalid CSRF token while the form is submitted from legitimate user(not faked).
**Please** check this [thread](http://stackoverflow.com/questions/10466241/new-csrf-token-per-request-or-not?lq=1) 
+ Adding expiry date is better for making it more secured.
2 . It's painful to re-write the following snippet in every view page.
```php
use Helpers\Session;
$token = trim($data['token']);
Session::set('token', $token);
```
Instead this should work 
```
<input type="hidden" name="csrf_token" value="<?= $data['csrf_token']; ?>" />
``` …
=> Update Csrf.php & Create Request.php

app/Core/Router.php
Thanks to @jimgwhit for testing the code on PHP7 :smiley:
=> Adjusted invokeObject method in router for PHP7

app/Helpers/Session.php
Adding check for key in pull and will return null instead of false on get (and pull too) so it doesn't get confusing when getting boolean from session. 
Can be breaking if you are now checking for === false on the return of get! But this will be better to get objects or mixed types (and not only strings) from session.
=> Adding check for key in pull and return null if key doesn't exists in session

app/Core/Router.php
I removed the content of DIR from the path so that when the project is not at the root of the url, autoDispatch, will work.  I also changed the way the method is called so that the parameters are more in line with what the route does.  That way, instead of receiving an array as parameters, you actually receive every parameter.
=> autoDispatch when project not at root and parameters not as array

app/Core/Router.php
Thought these might be useful. :all is really not that useful in RESTful pattern matching, and digits (:num) is not the only use case.
If you are using mongo you may want to do:
Router::get('users/(:hex)', 'Controllers\user@getOne');
Router::get('users/(:hex)/reset-password', 'Controllers\user@resetPassword');
If you are using uuid v4 for something:
Router::get('users/(:uuidV4)', 'Controllers\user@getOne');
Router::get('users/(:uuidV4)/reset-password', 'Controllers\user@resetPassword');
=> Extra route patterns for hexadecimal and uuid v4.

app/Helpers/Data.php
create_key default value is 32 not 35
=> Change typo error on create_key description

app/Helpers/Hooks.php
Instead of using die() when the $where is unknown it is now throwing an exception. Should be better, and less error prone.
And also removed unneeded else blocks after returning.
=> Improve hookhelper

.gitignore, public/index.php, system/Core/View.php
The Core\View.php was using $_SERVER[''] and DIR paths to get to the template path. Wasn't working of coarse.
=> Fix template path used by core\view. Added new define for the public folder.

app/Core/Logger.php
The whole error log was being read into memory which causes a memory limit exceed when the log is too big.
Instead of prepending it is now appending to the file with the APPEND flag on file_put_contents. This will not load the whole file into memory.
**Warning, will append instead of prepend to the log file!**
(Same as in 3.0 beta pull request for fixing it, but this one is still for the 2.* users.).
=> Fixing memory limit exceed when having a big log file (append)

system/Core/Logger.php
The whole error log was being read into memory which causes a memory limit exceed when the log is too big.
Instead of prepending it is now appending to the file with the APPEND flag on file_put_contents. This will not load the whole file into memory.
=> FIxing logger memory issues.

app/Config/config.php, app/Config/constants.php, system/Database/Engine/MySQLEngine.php, system/Database/EngineFactory.php, system/Database/Service/MySQLService.php, system/Helpers/PhpMailer.php
Refactoring the use of database engine factory, service and the PhpMailer extending helper to use the new configuration structure.
New use on creating a database connection. You can have multiple connection configs for database connection.
The config structure will be like:
```php
Config::set('database', array(
'default' => array(
'engine' => 'mysql',
'config' => array(
'host' => 'localhost',
'database' => 'dbname',
'user' => 'root',
'pass' => 'password'
)
)
));
```
The default will be used when not giving the name when creating engine with the factory.
Config:
```php
Config::set('database', array(
'default' => array(
'engine' => 'mysql',
'config' => array(
'host' => 'localhost',
'database' => 'dbname',
'user' => 'root',
'pass' => 'password'
)
),
'other' => array(
'engine' => 'mysql', …
```
=> Refactor Database engine/services and PhpMailer to use the new config structure

app/Controllers/Demo.php, system/Database/Engine/MySQLEngine.php
Now you can do it with or without:
```php
$result_plain = $engine->select('SELECT * FROM '.PREFIX.'car');
$result_plain = $engine->select('* FROM '.PREFIX.'car');
```
Remeber, we need to move the configs and add .dist.php after it, and add it to the gitignore when stable. So we could update the git without having to clear our personal configs each time.
=> The prefixing 'SELECT ' in the query (for mysql engine) can still be in the query.

public/templates/default/footer.php, public/templates/default/header.php
For more information see http://blog.getbootstrap.com/2015/11/24/bootstrap-3-3-6-released/
=> 3.0 - Upgrade Bootstrap to 3.3.6

app/Config/bootstrap.php, app/Config/config.php, app/Config/routes.php, scripts/makelinks.php, system/Modules/AbstractModule.php, system/Modules/Manager.php
This push-request introduce the Modules Management to SMVC 3.0
Right now, the Modules Management execute the bootstrap of active Modules, on the Framework boot stage, permitting to have and use **per Module** configurations. 
The Config entry for the active Modules, from **app/Config/config.php** is in an array of strings, containing the Modules name.
Typically, a file located in Module's **Config** directory, called **bootstrap.php** is executed if exists. For example, for a Module called **Blog**, its bootstrap file is located in:
```
/app/Modules/Blog/Config/bootstrap.php
``` 
The Module's bootstrap files should call the companion files, usually **config.php** and **routes.php**. When new constants, specifically for this Module are defined, they go on **constants.php**
An example …
=> Introducing the Modules Management and their bootstrapping

app/Config/constants.php, public/templates/default/header.php, system/Helpers/Tags.php, system/Logger.php
Refactoring of Constants. SITETITLE -> SITE_TITLE, SITEEMAIL -> SITE_EMAIL
This one will considerable simplify integration of our code with SMVC3 in future (because those constants we use us, as is, too), and let's be honest! Looks better and more readable! :smile: 
That's all to change in constants and definitions, in my opinion.
=>  Refactoring some SITE* Constants (SITETITLE and SITEEMAIL)

system/Helpers/Hooks.php
Will throw exception when $where isn't found in the hook helper.
=> Will throw exceptions instead of die() when where place isn't found

app/Core/Logger.php
Since php7 released, it had introducing Throwable interface for handle Fatal and recoverable errors that threw instances of EngineException,  which did not inherit from Exception.
=> Update Logger.php to handle \Throwable instead only \Exception 

app/Helpers/Session.php
currently this method only provide alert box with class="alert alert-success alert-dismissable" even the $sessionName is 'info','danger' or 'warning' (base on 4 alert box type on Bootstrap). With little change than this method can show alert box with class="alert alert-info alert-dismissable" , "alert alert-danger alert-dismissable" or "alert alert-warning alert-dismissable" depend on giving $sessionName parameter
=> style adjustment for message type

app/Config/config.php, app/Modules/Demo/Controllers/Database/Engine.php, app/Modules/Demo/Controllers/Database/Export.php, app/Modules/Demo/Controllers/Database/Service.php, app/Modules/Demo/Core/BaseController.php, system/Database/Engine.php, system/Database/Engine/Base.php, system/Database/Engine/MySQL.php, system/Database/Engine/SQLite.php, system/Database/Manager.php
This pull request introduce the refactoring of Database Engines, to avoid the redundant code and to consolidate the structure.
In principle, the common used methods from **MySQL** and **SQLite** engines are moved in a base one, called **\Nova\Database\Engine\Base** and used as parent.
In other hand, some changes are introduced:
The **insertAll** method become **insertBatch** and now is totally independent from **insert** one, which lose its ability to manage the multi-inserts, to simplify the code and those multi-inserts being a MySQL thingy. Then, under **SQLite Engine**,  the method **insertBatch** will nuke the fridge (go Exception).
The methods **update** and **delete** lose the ability to establish **LIMIT**s as being a MySQL thingy and, considered by us, permitting developing bad …
=> 3.0 - Final Phase, stage continued #12

app/Config/config.php, app/Core/BaseModel.php, bootstrap.php, system/Database/Engine.php, system/Database/Engine/Base.php, system/Database/Service.php, tests/Nova/Database/Engine/MySQLEngineTest.php, tests/Nova/Database/Engine/SQLiteEngineTest.php
Simplify the logic of Database Engines, permitting to configure the fetching return type with a single parameter instead of two.
The new parameter is **returnType**, with the following possible values:
**array** is equivalent with passing **PDO::FETCH_ARRAY**
**object** is equivalent with passing **PDO::FETCH_OBJ**
**className** is equivalent with passing **PDO::FETCH_CLASS** and to fetch a valid qualified a **Entity**, defined by a qualified Class Name (full namespace).
Also, in this pull-request is continued the work on **\App\Core\BaseModel** and new methods are implemented.
=> 3.0 - Final Phase, stage continued #19

app/Core/ClassicController.php, app/Core/ThemedController.php, app/Modules/Demo/Controllers/Models/RelationalModel.php, app/Modules/Demo/Models/Category.php, app/Modules/Demo/Models/Course.php, app/Modules/Demo/Models/Post.php, app/Modules/Demo/Models/Profile.php, app/Modules/Demo/Models/Student.php, app/Modules/Demo/Models/User.php, composer.json, public/.htaccess, scripts/nova_testing.sql, system/Config/bootstrap.php, system/Database/Connection.php, system/ORM/Engine.php, system/ORM/Model.php, system/ORM/Query/Builder.php, system/ORM/Relation.php, system/ORM/Relation/BelongsTo.php, system/ORM/Relation/BelongsToMany.php, system/ORM/Relation/HasMany.php, system/ORM/Relation/Joining/Pivot.php
Okay, now the ORM's **Model Relations** works as supposed into **hasOne, hasMany, belongsTo and belongsToMany** incarnations, still needing to be completed the **Pivot** engine for **belongsToMany** to permit saving the relations.
To note that **hasMany** and **belongsToMany** support basic QueryBuilding, permitting even commands similar to:
```php
$courses = $student->courses()->where('category_id', 3)->limit(20)->offset(40)->get();
```
=> Improve Nova\ORM and update the associated Demos and SQL file

nova/system/Core/Router.php
This PR improve the Routes Group management into **Core\Router** making possible the use of recursive definition of those groups of Routes.
Example:
```php
Router::group('admin', function() { 
Router::any('dashboard', 'App\Controllers\Admin\Dashboard@index');
Router::group('blog', function() {
Router::any('list', 'App\Controllers\Admin\Blog@list');
Router::any('add', 'App\Controllers\Admin\Blog@add');
Router::any('edit', 'App\Controllers\Admin\Blog@edit');
Router::post('delete', 'App\Controllers\Admin\Blog@delete');
});
Router::any('settings', 'App\Controllers\Admin\Settings@manage');
});
```
This command is equivalent with:
```php
Router::any('admin/dashboard', 'App\Controllers\Admin\Dashboard@index');
Router::any('admin/blog/list', 'App\Controllers\Admin\Blog@list'); …
```
=> Improve the Routes Group handling into Core\Router

system/Core/Route.php, system/Core/Router.php, system/Helpers/Response.php
This last minute PR introduce a **Multi-Method Route Match**, extremely useful when dealing with CRUD forms, while is wanted to specify punctually the valid request methods.
Usage:
```php
Router::match(['get', 'post'], 'admin/users/(:num)/edit', 'App\Controllers\Admin\Users@edit');
```
Or, in the **ClassicRouter** case can be:
```php
Router::match(['get', 'post'], 'admin/users/(:num)/edit', 'admin/users/edit/$1');
```
=> Add the support for multi-method Route Match

system/Net/Router.php
This PR introduce the ability to specify the Prefix and Namespace for the Route Groups and Resource(full) Routes.
The new **Router::group()** accept an array as first parameter and permit commands like:
```php
Router::group(['prefix' => 'admin', 'namespace' => 'App\Controllers\Admin'], function() {
Router::match('get',            'users',             'Users@index');
Router::match('get',            'users/create',      'Users@create');
Router::match('post',           'users',             'Users@store');
Router::match('get',            'users/(:any)',      'Users@show');
Router::match('get',            'users/(:any)/edit', 'Users@edit');
Router::match(['put', 'patch'], 'users/(:any)',      'Users@update');
Router::match('delete',         'users/(:any)',      'Users@destroy'); …
```
=> Improve the Routes Groups and implement the Resource(ful) Routes groups

system/Core/Router.php
Associated with the case presented by #715, right now the Routing doesn't support **Deep Grouping**, aka grouping the Routes until one of them come to have an empty "route" parameter. For example:
```php
Router::group('admin', function() {
Router::any('', 'App\Controllers\Admin\Dashboard@index');
...
});
``` 
This PR fix the behavior and permit to have that Deep Grouping.
=> Support the Deep Grouping into Routing

app/Routes.php, public/index.php, system/bootstrap.php
Rationale:
Right now, the Framework's bootstrap is divided in two files: **public/index,php** and **APPDIR.Routes.php**
This design permit using a unique file for bootstrapping the Framework and isolation between Routes definition and execution.
As collateral advantage, permit the creation, eventually, of a console command to **dump the Routes**, an very useful thing when the **Router::resource()**s are used.
=> Consolidate the Framework's bootstrap

system/bootstrap.php
Yet another small PR. Rationale:
If someone seriously mess with **app/Config.php** file, because our custom error handler is not yet active, the errors will be dumped to user into ol'good php way.
Solution? To move the setup of the error handler before everything into bootstrap stage run.
=> Improve the boostrap stage

app/Controllers/Demo.php, app/Controllers/Error.php, app/Controllers/Language.php, app/Routes.php, app/Views/Error/404.php, system/Core/Error.php, system/Core/Router.php
Right now Core\Error behave as Error fallback Controller for Routing and also as processor of errors.
Yet, I believe that is better to give to end-user the ability to customize as he wish the **Error Controller** and as he need (e.g. with custom templating), without to touch the System files and the associated View is already living into App/Views.
Spliting the **Core\Error**'s Controller part to **App\Controllers\Error** make, in my opinion, the framework to be more consistent and versatile, while not making the Routing to call system classes. After all, the Routing should call its App's Controllers, right?
In other hand, this PR adjust the **App\Controllers\Language** to become a real Controller and the associated Routing configuration affected by Error Controller change are updated.
=> Split the Core\Error Controller part to App\Controllers\Error

system/Core/View.php
Right now, **View::render()** use to have as third parameter an (legacy?) array of errors, while that parameter is not really necesary now, while the View rendering extract the parameters from the second parameter $data. 
In fact, if **$data** contains an element called "error", it will override the array passed as third parameter, logic prone to generate mysterious rendering errors per-se.
In other hand, passing as third parameter the optional name of the Module, just like into **View::fetch()** is of nature to simplify the View class design (literally making obsolete the **View::renderModule()**), to offer a consistent API with **View::fetch()** and **View::renderTemplate()** and, why not? to offer an alternative to writing **View::renderTemplate()**'s long commands.
Then, instead of: …
=> Make the third parameter of View::render() to be an (optional) Module name

app/Filters.php, app/Routes.php, system/Core/Route.php, system/Core/Router.php, system/Helpers/Response.php, system/bootstrap.php
After the implementation of **Controller's Middleware**, the current pull request introduce the **Routing Middleware**, implemented using the concept of the **Route Filters**.
For what they are good for, comparative with Controller's **before()** and **after()** ?
The Controller's Middleware, aka **Controller Execution Flow** represents a High Level processing API, **executed by the requested Controller**, when it is instantiated, its requested Method is know as being valid and callable, and working in the same flow as your wanted Method.
The graph of **The Controller Execution Flow** is as follow:
**before() -> action() -> after()**
While very efficient and accurate, sometimes this design is not the best. For example, to instantiate a Controller and start its Execution Flow, only to …
=> Implementation of Route Filters support into Routing and other improvements

system/Core/Controller.php, system/Core/Template.php, system/Core/View.php
In almost any of Big Houses of frameworks, the **View** Class deal with a single **VIEWS PATH**. 
Under Nova, behind **Views**, we have also the concept of **Templates**, which have their own design and concept. 
Dealing with Template files in the same **View** class make us to complicate its design an can be confusing for end-users some of them looking to have problems to understand the inherited difference between a **View file** associated to a Controller and its Method, and a Template file, who give you (parts of) Layouts, even when using the ol'good **Triplet Style Rendering**.  
I consider that is not better to continue this confusion maker situation even into the New Style Rendering API and it better to have a dedicated class who deal with the Template Files.
Enter the …
=> Introducing Core\Template, a View specialized to handle Template files

system/Core/View.php
It is supposed that **View::nest()** and **Template::nest()** always will nest a local generated **View instance**.
This very simple patch ensure that logic.
=> Consolidate Core\View

app/Controllers/Demo.php, system/Core/BaseView.php, system/Core/ClassicRouter.php, system/Core/Controller.php, system/Core/Router.php, system/Core/Template.php, system/Core/View.php
This Pull Request introduce a new class, called **Core\BaseView**, which is the base for **Core\View** and **Core\Template**, and contains their common logic. This way, the code of Rendering is simplified.
To note that this Pull Request remove the Compat Layer for **View::renderModule()**, its functionality being supported completely by **View::render()**, as its third parameter being the optional **Module** name, and for now we throw a meaningful Exception for.
Also to note that removing the Compat Layer for **View::renderModule()** sensible simplify the **Core\View** and **Core\Template**. 
Finally, this Pull Request introduce improvements on Routing.
=> Remove the Core\View@renderModule support, improve the logic on Core\View@offsetGet and the properties getter

app/Controllers/Welcome.php, app/Templates/Default/default.php, app/Templates/Default/header.php, system/Core/Aliases.php, system/Core/BaseView.php, system/Core/Controller.php, system/Core/Language.php, system/Core/Template.php, system/Core/View.php, system/Helpers/Response.php, system/functions.php
To note that this pull request introduce two new useful helper functions:
```php
resource_url($path, $module = null);
template_url($path, $template = TEMPLATE, $folder = '/assets/');
```
Finally, this pull-request introduce the ability to use dynamic methods **shareX** into **Core\View** and **Core\Template** classes. Usage:
```php
return View::make('Welcome/SubPage', $data, 'Home')->shareTitle($title);
```
=> Reorder the new Language codes and adjust the Language changer; make the default Layout stand-alone

system/Database/Model.php, system/Database/Query.php
Remove the support for handing the **Database\Model** data on **Database\Query** and simplify it.
=> Make the Database\Query agnostic about the current used Database\Model

app/Controllers/Users.php, app/Views/Users/Profile.php, system/Auth/Guard.php
This pull request introduce improvement into **Auth System** and new methods into **Auth\Guard** API, exposed via **Auth\Auth** Facade. Notable, there is **Auth::id()** which returns the current authenticated User **ID**, or **null** for Guests. Usage is simple:
```php
$userId = Auth::id();
// Do something with userId.
```
Also, is introduced the ability to store and retrieve a boolean flag about login via Cookie, usable as:
```php
if(Auth::viaRemember()) {
// User authenticated via Cookie; do something about...
}
```
=> Improve the Auth System

app/Config.example.php, app/Controllers/Users.php, app/Views/Users/Profile.php, system/Auth/Auth.php, system/Auth/Guard.php
This pull request introduce the ability to specify into configuration the Users Table columns used by **Auth\Guard**.
Also, there is introduced a improved **Auth\Auth** Facade, which is now extensible, permitting to register on it new third-party Authentication Guards.
=> Improved Auth\Auth; make configurable the Table columns used by Auth\Guard

system/Database/Query.php, system/Database/Query/Join.php
This pull request do **not** introduce API breaks, **Database\JoinClause** being for internal use into **Database\Query**
=> Move Database\JoinClause to Database\Query\Join

app/Cache/.gitignore, app/Config.example.php, composer.json, system/Database/Query.php, system/Helpers/FastCache.php
This pull request introduce a very simple **Cache** Helper, built in top of **phpFastCache**, and called **Helpers\FastCache**. Its usage is very simple:
```php
use Helpers\FastCache;
$cache = FastCache::getInstance();
// Use any phpFastCache methods on FastCache instance.
```
To note that the **Helpers\FastCache** practically acts like a **Decorator** for phpFastCache, then could be called any phpFastCache method, its API applying.
Also, note that this pull request introduce a new directory into App, called **Cache**, to store the Cache files.
=> Implementing a simple Cache Helper in top of phpFastCache

app/Config.example.php, app/Controllers/Demo.php, app/Events/Test.php, system/Events/Dispatcher.php, system/Events/Facade.php, system/functions.php
This pull request introduce a simple **Events\Dispatcher**, in a Laravel-esque style, and its associated **Facade**.
The idea behind the Events is the ability to send data, as parameters, to interested **Listeners** and call them, when a Event happen. The Listeners could be a Closure or **static** Class Method. 
To note that the  **Events\Dispatcher** do **not** instantiate a Listener's Class, then the called method is a must to be **static**.
Its usage is simple; first we have to register a **Listener**, adding:
```php
use Event;
// Add a Listener to the Event 'test'.
Event::listen('test', 'App\Events\Test@handle');
```
Where the class **App\Events\Test** is
```php
namespace App\Events;
class Test
{
public static function handle($message)
{
echo $message;
}
}
```
Then, when is need, we …
=>  	Implementing a simple Events management

app/Events/Test.php, system/Database/Model.php, system/Events/Dispatcher.php
This pull-request introduce improvements into **Events\Dispatcher** as in support for Queued Events and a new method **Events\Dispatcher@until**.
The **Queued Events** is a method to add a number of **Events** to a **Queue**, then firing them together, flushing the Queue. E.g
```php
// Queue the Events
Event::queue('test', array('This is the First Event'));
Event::queue('test', array('This is the Second Event'));
Event::queue('test', array('This is the Third Event'));
// Flush the Queue, firing all defined Events
Event::flush('test'); 
```
The new method **Events\Dispatcher@until** is about firing a Event **until** first **Listener** returns a valid and non-null response, which will be returned. Its usage is simple:
```php
$response = Event::until('testing', $payload);
if($response !== …
```
=> Improve Events\Dispatcher

app/Config.example.php, system/Core/Modules.php, system/bootstrap.php
This pull-request introduce a simple but enhanced Modules configuration, using  a new Class called **Core\Modules**. Basically, now every Module can be considered a **min-App**, sporting its own **Config.php**, **Filters.php** and **Routes.php**, with functionality similar with the main ones.
To properly work, a App Configuration entry was added, and there should be specified the **active** Modules, the **Core\Modules** looking only for those specified by name there. E.g.
```php
Config::set('modules', array(
'Users',
'Blog',
'Articles',
));
```
=> Improve the Modules Configuration management

system/Core/Request.php, system/Core/Template.php
=> Adjust Core\Template for better compatiblity with PHP7

app/Config.example.php, app/Controllers/Demo.php, app/Routes.php, composer.json, system/Cookie/CookieJar.php, system/Core/Base/View.php, system/Database/ORM/Model.php, system/Http/JsonResponse.php, system/Http/RedirectResponse.php, system/Http/Request.php, system/Http/Response.php, system/Session/Store.php, system/Support/Contracts/ArrayableInterface.php, system/Support/Contracts/JsonableInterface.php, system/Support/Contracts/MessageProviderInterface.php, system/Support/Contracts/RenderableInterface.php, system/Support/Contracts/ResponsePreparerInterface.php, system/Support/Facades/Cookie.php, system/Support/Facades/Input.php, system/Support/Facades/Language.php, system/Support/Facades/Redirect.php, system/Support/Facades/Request.php, system/Support/Facades/Response.php, system/Support/Facades/Validator.php, system/bootstrap.php
This pull request introduce a implementation of a simple but very powerful **Request API**, built in top of **Symfony HTTP Foundation**, and being similar with its counterpart **Laravel 4.x**, of what documentation apply, excluding the **Session** part, which is not (yet) completed / integrated with the Framework.
The objective is to create a fully functional support for HTTP Requests, even for complicated RESTful APIs, in the same time to simplify the input data handling on a daily base.
The usage could be very simple, as in following example, together with the **Validator**:
```php
use Validator;
use Input;
$rules = array(
'username' => 'required|min:3|max:50|alpha_dash|unique:users',
'password' => 'required|between:4,30',
'email'    => 'required|email|max:100|unique:users',
);
// …
```
=> Implementation of a Laravel-esque Request, Input (and Response) support

system/Validation/Validator.php
No API changes there, just completing the (uploaded) files associated validation rules as presented into Illuminate\Validation 4.x
Example usage of the new supported Validation Rules:
```php
$rules = array(
'file'=>'image|max:2048000',
);
```
To note that Files validation works only when is used the new **Request API**, then you could have:
```php
use Input;
use Validator;
$rules = array(
'file'=>'image|max:2048000',
);
$data = Input::all();
$validator = Validator::make($data, $rules);
if($validator->passes()) {
// Do some shiny things there; the uploaded file is valid.
} else {
$errors = $validator->errors()->all();
// Do nasty things there; the User uploaded a strange file...
}
```
=> Introduce the (uploaded) Files validation on Validation\Validator, on top of the new Request API

system/functions.php
Reverts nova-framework/framework#873
Reverted as  _e() are not detected by the Language Files Updater, then those translations will fail
=> Revert "Update functions.php"

system/Helpers/Database.php
This pull request improve the **Helpers\Database** and integrate it with the **Database API**, making possible to use it even when Database API is used too, without to duplicate the database connections.
The single visible change in API is that the optional parameter of the method **Database::get()** is now a string, defaulting to **'default'**, and indicating the **Database API** configuration entry used, instead of being a configuration array. Usage is simple:
```php
// Get the default Database instance
$db = Database::get();
// Get a custom configured Database instance
$customDb = Database::get('custom');
```
**To note that the API remains unchanged in the rest.**
=> Improve the Helpers\Database and integrate it with the Database API

app/Modules/Users/Views/Users/Login.php, system/Core/BaseView.php, system/Core/Controller.php, system/Database/ORM/Model.php
This pull request introduce a simple but very handily improvement of **Core\Controller**, making it capable to transparently call a View instance, if the developers accept to use a implicit View for the Controller's method.
As a example of the usage for the Controller **App\Controllers\Welcome**:
```php
public function subPage()
{
$this->title($this->trans('subpageText'));
return $this->getView()
->withWelcomeMessage($this->trans('subpageMessage'));
}
```
Another example, for **App\Modules\Users\Controllers\Users**:
```php
public function login()
{
$error = Session::remove('error', array());
$this->title(__d('users', 'User Login'));
return $this->getView()
->with('csrfToken', Session::token())
->with('error', $error);
}
```
How it is calculated the implicit View path?
It is the calculated …
=> A simple but very handily improvement of Core\Controller

app/Config.example.php, app/Config/Routing.php, app/Modules/Users/Models/Users.php, system/Routing/ClassicRouter.php, system/Routing/Route.php, system/Routing/Router.php
This pull request make the Nova's **Routing** configurable via the file **app/Config/Routing.php**, which usually contains:
```php
/**
* Routing configuration
*/
Config::set('routing', array(
'patterns' => array(
//':hex'    => '[[:xdigit:]]+',
//':uuidV4' => '\w{8}-\w{4}-\w{4}-\w{4}-\w{12}'
),
'default' => array(
'controller' => DEFAULT_CONTROLLER,
'method'     => DEFAULT_METHOD
)
));
```
In the **"patterns"** array entries could be added additional **Routing Patterns** used by the both Routers, while the **"default**" entry is for the **ClassicRouter**.
Finally, this pull request introduce a **small optional feature**: the **Named Patterns** which are practically aliases to **(:any)** and  **(:num)**, but permitting a more fluent definition, for example:
```php
// Using a :ANY based …
```
=> Make the Routing configurable via app/Config/Routing.php

app/Config/App.php, app/Modules/Users/Views/Admin/Roles/Index.php, system/Core/Controller.php, system/Helpers/Url.php, system/Routing/BaseRouter.php, system/Routing/ClassicRouter.php, system/Routing/Router.php, system/Support/Facades/App.php, system/Support/Facades/Session.php
This pull request introduce a split the Application finishing logic from **Support\Facades\Session** to **Support\Facades\App**.
To note that because the affected logic by this change is **internal used API**, there are **no public API changes or breaks**.
=>  	Split the Application finishing logic from Support\Facades\Session to Support\Facades\App

app/Config/Database.php, app/Controllers/Welcome.php, scripts/nova_roles.sql, scripts/nova_testing.sql, system/Database/Connection.php, system/Database/DatabaseManager.php, system/Database/Model.php, system/Database/ORM/Model.php, system/Helpers/Database.php
This pull request improve the logic on **Database\Connection** and make its configuration more versatile.
A typical Database configuration looks now as following:
```php
/**
* Setup the Database configuration.
*/
Config::set('database', array(
// The PDO Fetch Style.
'fetch' => PDO::FETCH_CLASS,
// The Default Database Connection Name.
'default' => 'mysql',
// The Database Connections.
'connections' => array(
'sqlite' => array(
'driver'    => 'sqlite',
'database'  => APPDIR .'Storage' .DS .'database.sqlite',
'prefix'    => '',
),
'mysql' => array(
'driver'    => DB_TYPE,
'hostname'  => DB_HOST,
'database'  => DB_NAME,
'username'  => DB_USER,
'password'  => DB_PASS,
'prefix'    => PREFIX,
'charset'   => 'utf8',
'collation' => 'utf8_general_ci',
),
'pgsql' => array(
'driver'   => 'pgsql', …
```
=> Improve Database\Connection and its configuration; update the SQL scripts

app/Controllers/Welcome.php, app/Modules/Settings/Views/Admin/Settings/Index.php
This pull request disable the Settings given by the Settings Module, when the Config Store is on (native) Files Mode.
=> Disable the Settings when the Config Store is on Files Mode

system/Core/Controller.php, system/Routing/ControllerInspector.php, system/Routing/Router.php
This pull request allows you to easily define a single route to handle every action in a controller. 
First, define the route using the Route::controller method:
```php
Route::controller('users', 'App\Controllers\Users');
```
The `Route::controller()` method accepts two arguments. The first is the base URI the controller handles, while the second is the class name of the Controller. Next, just add methods to your Controller, prefixed with the HTTP verb they respond to:
```php
class App\Controllers;
use Core\Controller;
class Users extends Controller 
{
/**
* Call the parent construct
*/
public function __construct()
{
parent::__construct();
}
public function getIndex()
{
//
}
public function postProfile()
{
//
}
public function anyLogin()
{
//
}
}
```
The index methods will respond to the …
=> Implementation of Routing support for Implicit Controllers

app/Filters.php, system/Foundation/Application.php, system/Routing/ControllerDispatcher.php, system/Routing/Route.php, system/Routing/RouteFiltererInterface.php, system/Routing/Router.php
This pull request introduce the implementation of Global Routing Filters and move the Filters to a Events based approach.
The design now permit assigning multiple Filter commands to the same filter, assigning also Global Filters, via `App::before()` and `App::after()`.
No API changes, but introducing new small features.
=> Implementation of Global Routing Filters and move the Filters to a Events based approach

system/Core/Controller.php, system/Routing/AssetFileDispatcher.php, system/Routing/Controller.php, system/Routing/ControllerDispatcher.php, system/Routing/ControllerInspector.php
This pull request split the base processing from Core\Controller to Routing\Controller, for RESTful optimization.
The new **Routing\Controller** have no theming support, perfect for Controllers which do not generate pages, while **Core\Controller** continue to have support for theming, as usual.
No API changes there, good for a micro version release.
=> Split the base processing from Core\Controller to Routing\Controller, for RESTful optimization

system/Core/Controller.php, system/Routing/Controller.php
This pull request introduce a small change on Controller's Middleware behavior, being accepted any type of response from Before Stage.
Basically, the Controller's Action will be executed only when Before Stage return a null response, then permitting to `before()` to return any valid response, for example, a string, a View instance, etc.
=> Accept any type of response from Before Stage on Routing\Controller

app/Controllers/Demo.php, app/Routes.php, system/Routing/Route.php, system/Routing/RouteCollection.php, system/Routing/Router.php
This pull request introduce on Routing a set of educated Route compilers which manage to give the same pattern for Routes matching for both Named and Unnamed Parameters.
To be read: the Routes matching will always give you named parameters, but in the case of Unnamed Parameters they will be named like "paramX", where X is is a number.
In other hand, the Named Parameters adopt the Nova 4 style for custom patterns - via **where()**s, examples given.
NO API Breaks, just some changes on syntax of the Named Parameters, but who use that yet, excluding me?
=> Unify the Named and Unnamed Routes compilation on Routing

app/Controllers/Demo.php, system/Routing/Route.php, system/Routing/RouteCompiler.php
This pull request introduce some small improvements on Routing and separate the Named vs. Unnamed Parameters processing via a configuration option on **app/Config/Routing**, defaulting to Named Parameters.
The reason is that auto-switching is not a perfect solution, because a pattern which have mixed styles would never work, even if we claim that Nova 3 support both styles. For example:
```php
Router::any('blog/(:any)/(:any)/{slug?}', 'App\Controllers\Demo@request')->where('slug', '.*');
```
And that could be confusing.
In other hand, looks like our end-users have no problems to assimilate fast the knowledge required by the {named} parameters, also considering that on Nova 4 is the only style applicable, then a application using them will have less issues on porting to the next major …
=> Rename the property 'pattern' as 'regex' on Routing\Route and improve Routing\RouteCompiler

app/Config/App.php, app/Controllers/Welcome.php, app/Modules/Demos/Controllers/Demos.php, app/Modules/Demos/Routes.php, app/Modules/Files/Controllers/Admin/Files.php, app/Modules/System/Controllers/Admin/Dashboard.php, app/Modules/System/Controllers/Admin/Profile.php, app/Modules/System/Controllers/Admin/Settings.php, app/Modules/System/Controllers/Authorize.php, app/Modules/System/Controllers/CronRunner.php, app/Modules/System/Controllers/Language.php, app/Modules/Users/Controllers/Admin/Roles.php, app/Modules/Users/Controllers/Admin/Users.php, app/Modules/Users/Controllers/Registrar.php, app/Routes.php, system/Cli/ControllerCommand.php, system/Core/Controller.php, system/Database/Model.php, system/Helpers/Database.php, system/Helpers/Profiler.php, system/Support/Facades/View.php
This pull request move the **Core\View Facade** to namespace **Support\Facades** and introduce overall small improvements. 
Also, are provided the compatibility class aliases for **Core\Template** and **Core\View**.
Finally, the Cache demo is moved to using the **Cache Service** instead of **Helpers\FastCache**.
**No API changes**, good for a micro version release.
=>  	Move the Core\View Facade to namespace Support\Facades and overall small improvements

system/Database/ORM/Relations/BelongsToMany.php, system/Routing/Legacy/RouteParser.php, system/Routing/Route.php
The Symfony's Route Compiler treat separately the domain and URI patterns, every on having the ability to contain (named) parameters, while on Unnamed Parameters mode, the Routing parse only the URI pattern, as supposed by the compatibility mode.
This pull request fix a possible logic issue while the Routing is on Unnamed Parameters mode, going Exception while is used the **domain** option or the `where()` command.
To note that the use of the classic SMVC-like pattern style (aka the Unnamed Parameters mode) is not influenced.
Also, this pull request introduce a bug-fix on **Database\ORM\Relations\BelongsToMany**.
=> Bugfix on Database ORM, consolidate the Routing - no domain option and custom patterns are allowed while using Unnamed Parameters

system/Support/Facades/View.php, system/View/Factory.php, system/View/View.php
This pull request add a small feature to View Service, offering the support for `View::fetch()` command, which, internally, create a View instance, then render it and returns the result.
As a side note, you will notice that this method, `View::fetch()` is similar with one offered by the Views Legacy Layer, which was previous removed. 
But this time, the command is one native integrated on **View\Factory** and considered being very useful for local rendering, was added back.
Finally, is introduced also a small fix on **View\View**, as in a missing `use`.
=> Adding a small feature to View Service, offering the support for View::fetch()

app/Templates/AdminLTE/backend-rtl.php, app/Templates/AdminLTE/backend.php, app/Templates/AdminLTE/default-rtl.php, app/Templates/AdminLTE/default.php, app/Templates/Default/default.php, app/Views/Error/500.php, system/functions.php
This pull request add a new helper function called `vendor_url()`, with a convenience role. 
Its usage is for Layouts and is simple as:
```php
vendor_url('dist/css/AdminLTE.min.css', 'almasaeed2010/adminlte'),
```
The rationale of adding it is that its logic expose better to the rogrammer logic the vendor files.
=> Implement the function vendor_url() and add the missing file app/Views/Error/500.php

app/Boot/Global.php, app/Filters.php, app/Modules/System/Controllers/Authorize.php, app/Modules/System/Routes.php, app/Modules/System/Views/Authorize/Reset.php, system/Support/Facades/Response.php
This pull request improve **the HTTP Exceptions handling**, simplifying and unifying the logic, making possible to expose the entire Error Pages generation to the end-user, them making possible their customization as Template, Layout, etc.
As a collateral consequence, the `Response::error()` was removed, not being useful anymore.
As usage, basically we will go back to roots, using for aborting of the processing, the `App::abort()` which exists there since ages. For example, if you want to go **Error 404** in your Controller's Action, you can use:
```php
App::abort(404, 'Page not found');
```
Same way for going i.e. **Error 400**
```php
App::abort(400, 'Bad Request');
```
=> Improve the HTTP Exceptions handling

app/Config/FileField.php, shared/Database/ORM/FileField.php, shared/Database/ORM/FileFieldTrait.php, shared/Database/ORM/README.md
Easily upload files to a directory and save the filename to database attribute.
In your ORM Model:
```php
use Shared\Database\ORM\FileFieldTrait;
public $files = array(
'image' => array(),
'poster' => array(
'path' => 'uploads/:class_slug/:attribute/:unique_id-:file_name',
'defaultPath' => 'uploads/default.png'
)
);
```
In your Controller:
```php
$model = new Poster();
if (Input::hasFile('poster')) {
$model->poster = Input::file('poster');
}
$model->save();
```
Each field can have filesystem path pattern and default path options. If you don't specify any of them, they will be loaded from default config.
=> Implementation of the ORM File Field

app/Boot/Global.php, app/Config/App.php, app/Core/Controller.php, app/Templates/AdminLTE/backend-rtl.php, app/Templates/AdminLTE/backend.php, app/Templates/AdminLTE/default-rtl.php, app/Templates/AdminLTE/default.php, app/Templates/Default/default-rtl.php, app/Templates/Default/default.php
For a better description, the **Template Service** was renamed as **Layout**, because what it handle really are the Layout files.
Also, this renaming leave room for a future **Template Service** for handling the whole Templates, similar with the Modules one.
=> Adjust the application to support the renaming the Template Service as Layout
